"""Additional original fictional reading scenarios."""
EXTRA_STORIES = [
('stargazing','space','星を見る会と曇り空','B1','space|moon|tree',[
('An astronomy club planned an evening for beginners at a local park. The invitation promised a chance to learn how to find objects in the night sky, but it did not guarantee a clear view. On the afternoon of the event, clouds began to gather, and several visitors asked whether they should still come.','天文クラブは公園で初心者向けの夜の会を計画した。案内には夜空の天体を探す方法を学べると書いたが、晴れた眺めは保証しなかった。当日の午後に雲が集まり、参加するべきか尋ねる人が出た。'),
('The organizer checked the latest forecast and called the park office. The group had permission to use a sheltered meeting space nearby, so she decided to keep the event but change its order. Visitors would begin with a short introduction indoors, then go outside if the conditions improved enough to observe safely.','主催者は最新の予報を確認し、公園事務所に電話した。近くの屋根のある集会場所を使う許可があったので、開催は続けて順番を変えることにした。屋内の短い説明から始め、安全に観察できるまで天候がよくなったら外へ出る。'),
('Inside, a volunteer demonstrated how to handle the equipment without pushing the telescope out of position. Each visitor practiced adjusting an empty stand before approaching the instrument. Another member showed a sky map and explained why a printed picture should not be treated as a promise of what every person would see.','屋内ではボランティアが望遠鏡の位置をずらさず扱う方法を示した。参加者は機器に近づく前に何も載っていない台を調整してみた。別の会員は星図を示し、印刷された写真と同じものが全員に見えるという約束ではないと説明した。'),
('Later, the clouds opened briefly. The group took turns rather than crowding around the telescope. Some visitors saw the intended object clearly, while others needed help with the viewing position. When the sky became cloudy again, the organizer invited questions instead of encouraging people to report details they had not actually noticed.','その後、短時間雲が切れた。望遠鏡に群がらず交代で見た。目的の天体がはっきり見えた人もいれば、のぞく位置の助けが必要な人もいた。再び曇ると、主催者は実際に気づかなかった細部を報告するよう促すのでなく質問を受け付けた。'),
('Before leaving, participants wrote one observation and one question in a notebook. The club shared instructions for a future session, including what to bring and how cancellations would be announced. Although the sky had not cooperated for long, the visitors had practiced observing carefully and distinguishing what they saw from what they expected.','帰る前に参加者は観察したこと一つと疑問一つをノートに書いた。クラブは持ち物や中止の案内方法を含め次回の説明を共有した。空の状態は長くはよくなかったが、丁寧に観察し、見たことと期待したことを区別する練習ができた。')],
[('What did the invitation guarantee?',['A perfectly clear sky','A chance to learn','A photograph for everyone'],1),('Where did the event begin?',['In a sheltered space','At a train station','On a roof'],0),('What did visitors write?',['Only equipment prices','A weather forecast','An observation and a question'],2)]),
('poster','art','遠くから読めるポスター','B1','paper|palette|book',[
('A volunteer group designed a poster for a weekend repair event. Residents could bring a broken household item and ask volunteers whether it could be repaired. The first design contained a colorful illustration, a long explanation of the project, and the names of every organization that had offered support.','ボランティア団体が週末の修理イベントのポスターを作った。住民は壊れた家庭用品を持ち込み、修理できるか相談できる。最初の案には鮮やかな絵、長い事業説明、支援団体すべての名前が入っていた。'),
('The designer printed a sample and placed it on a noticeboard. From a few steps away, the illustration was easy to recognize, but the date and location were difficult to read. A passerby thought the event was a sale because the words explaining the repair service were smaller than the decorative heading.','デザイナーは見本を印刷して掲示板に貼った。数歩離れると絵は分かるが日時と場所は読みにくかった。修理サービスの説明が飾りの見出しより小さいため、通行人は販売会だと思った。'),
('The team listed the questions a new visitor would need answered. What could they bring? When should they arrive? Was a repair guaranteed? They rewrote the main message around those questions and moved the longer background explanation to a separate information sheet available at the venue.','チームは初めて来る人が知りたい問いを挙げた。何を持参できるか。いつ来ればよいか。修理は保証されるか。その問いに沿って主要な説明を書き直し、詳しい背景は会場で渡す別紙へ移した。'),
('In the second version, the event title, date, and address were the largest text. A short sentence explained that some items might not be repairable. The team tested the poster with people who had not attended the planning meetings. They asked what the poster meant before describing what they had intended it to mean.','2案目ではイベント名、日付、住所を最大の文字にした。修理できない品もあると短く説明した。企画会議に参加していない人に試した。意図を説明する前にポスターの意味を尋ねた。'),
('The final poster was simpler, but the illustration still gave it a friendly character. On the event day, volunteers compared visitors’ questions with the information on the poster. They saved notes for the next design, recognizing that a clear message should be judged by how people understand and use it.','完成版は簡潔になったが、絵による親しみやすさは残った。当日、ボランティアは来場者の質問と掲示した情報を比較した。明確なメッセージは人々の理解と利用によって判断すべきだと考え、次のデザインのために記録を残した。')],
[('What was hard to read initially?',['The illustration','The decorative heading','The date and location'],2),('Who tested the second version?',['People outside the planning meetings','Only the designer','Only the sponsors'],0),('What was not guaranteed?',['A colorful poster','A successful repair','A venue address'],1)]),
('running','sport','初めてのランニングクラブ','B1','day|ball|clock',[
('When Emi joined a neighborhood running club, she expected everyone to follow the same route at the same speed. At the first meeting, however, the organizer asked members about their experience and goals. Some wanted company for a relaxed outing, while others were preparing for an event later in the year.','エミは近所のランニングクラブに入り、全員が同じ道を同じ速さで走ると思っていた。しかし初回、主催者は経験と目標を尋ねた。気軽に走る仲間が欲しい人も、年内の大会に向けて準備する人もいた。'),
('The organizer described two routes that started and finished at the same meeting point. Participants could choose a shorter route, and nobody would be left alone at the back. Emi joined a group that planned to alternate walking and running. She felt more comfortable knowing how the session would work before it began.','主催者は同じ地点を発着する二つの道を説明した。短い道を選べて、最後尾で一人にされる人はいない。エミは歩行と走行を交互にするグループに加わった。始まる前に進め方が分かり安心した。'),
('Halfway through the route, one member suggested a faster pace. Another said that the change would make conversation difficult. Instead of treating the disagreement as a competition, the group referred to its original plan. The faster runner joined a different group at the next agreed meeting point, and Emi continued with her partners.','途中、一人がペースを上げようと提案した。別の人は会話が難しくなると言った。意見の違いを競争と考えず最初の計画を確認した。速く走る人は次の集合地点で別のグループに加わり、エミは仲間と続けた。'),
('After the session, the members discussed more than distance and time. They checked whether the route was easy to follow and whether everyone understood the meeting arrangements. Emi mentioned an unclear turning point near a bridge. The organizer added that location to the route description for the following week.','終了後は距離や時間以外も話した。道順は分かりやすいか、集合方法を全員が理解したか確認した。エミは橋の近くの曲がり角が分かりにくいと言った。主催者は翌週の案内にその場所を加えた。'),
('Emi decided to return because the group had listened to different preferences. She wrote down what she had enjoyed and one question to ask next time. Her first goal was to build a routine she could continue, rather than using another member’s pace as the only measure of a successful afternoon.','異なる希望に耳を傾けるグループだったので、エミはまた来ることにした。楽しんだことと次回の質問を書いた。最初の目標は、他の会員の速さだけで成功を測るのでなく、続けられる習慣を作ることだった。')],
[('What did Emi initially expect?',['Different activities every minute','The same route and speed for everyone','No meeting point'],1),('How was the pace disagreement handled?',['By referring to the plan','By cancelling the club','By leaving Emi alone'],0),('What did Emi report?',['A missing payment','A race result','An unclear turning point'],2)]),
('survey','math','アンケートの数字を読む','B1–B2','paper|chart|magnifier',[
('A student council wanted to extend the opening hours of its study room. To support the proposal, one member created an online survey and shared it in a group used by students who studied late. Most replies favored longer hours, and the team prepared a headline saying that students clearly supported the change.','学生自治会は自習室の利用時間を延ばしたかった。提案を支えるため、ある会員がオンライン調査を作り、夜遅く勉強する学生のグループで共有した。大半が延長に賛成し、チームは学生が明確に支持しているという見出しを用意した。'),
('Before publishing the result, Aya asked who had actually received the link. Students who left campus early might not belong to that group. Their reasons could include work, family responsibilities, or a preference for studying elsewhere. A large number of replies from one group would not automatically describe the views of everyone on campus.','発表前にアヤは誰にリンクが届いたか尋ねた。早く帰る学生はそのグループに入っていないかもしれない。仕事、家庭の責任、別の場所を好むことなど理由はさまざまだ。ある集団の回答が多くても、それだけで全学生の意見を表すわけではない。'),
('The council revised the headline to describe the respondents rather than all students. It also shared a second invitation through several channels and made the question more specific. Instead of asking whether longer hours sounded useful, it asked which additional time periods people expected to use and how often they might visit.','自治会は全学生でなく回答者について述べる見出しに変えた。複数の経路でもう一度案内し、質問も具体化した。延長が便利そうかではなく、追加するどの時間帯に、どのくらいの頻度で利用しそうかを尋ねた。'),
('The new responses showed different needs, but the team still did not treat intentions as guaranteed attendance. It proposed a short trial and a method for counting actual visits without collecting unnecessary personal details. Staff costs and building access also had to be considered before a permanent change could be approved.','新しい回答には異なる需要が見えたが、利用の意向が実際の参加を保証するとは考えなかった。短期試行と、不要な個人情報を集めず実際の利用を数える方法を提案した。恒久変更の前に職員費用や建物への出入りも考慮する必要があった。'),
('In its final report, the council separated survey responses, trial observations, and recommendations. Readers could see what each conclusion depended on. Aya was pleased that questioning the first result had improved the proposal rather than stopped it. The numbers became more useful when their limits were made visible alongside their practical meaning.','最終報告では調査回答、試行での観察、提案を分けた。各結論が何に基づくか読者に分かった。最初の結果を疑ったことで提案が止まらず改善し、アヤは喜んだ。数字は実用的な意味と限界を一緒に示すことで役立った。')],
[('What was the problem with the first survey?',['It reached a particular group','It contained no answers','It counted actual visits'],0),('What did the revised headline describe?',['Every resident','The respondents','Only library staff'],1),('Why propose a trial?',['To guarantee attendance','To avoid all costs','To observe actual use'],2)])
]
