/* Per-phoneme pronunciation check (General American). Each phoneme is a video lesson:
   slides = model words + sentence, "音素チェック" = mouth diagram, how-to, pitfalls, speech check, record & compare;
   "聞き分け" reuses the minimal-pair listening mode (pairs = [target word, contrast word]). */
// [key, IPA, group, Japanese name, place, voiced?, how, pitfall, words, pairs "target/contrast,...", sentence]
const PH_RAW=[
['p','p','破裂音','P（唇で破裂）','bilabial',0,'唇を閉じて息をため、一気に開く。語頭では強い息（手のひらに息が当たる）を伴う。','息が弱いと b に聞こえる（pie が buy に）。語末に「プ」と母音を足さない。',['pen','paper','price','report','shop'],'pat/bat,pie/buy,pin/bin,cap/cab,pack/back','Please pay the printing company by April.'],
['b','b','破裂音','B（唇で破裂・有声）','bilabial',1,'唇を閉じてから声を出しながら開く。','v を b で代用しがち（very が berry に）。b と v を言い分ける練習をする。',['book','budget','board','job','cabinet'],'berry/very,ban/van,boat/vote,best/vest,bet/vet','The board approved the budget for the new building.'],
['t','t','破裂音','T（舌先で破裂）','alveolar',0,'舌先を上の歯ぐきに付けて息をため、はじくように離す。母音にはさまれると軽い d に近くなる（water）。','「トゥ」「ツ」と母音を足す。tu は「ツ」にならないよう舌先を歯ぐきから離す。',['time','ticket','contract','meet','twenty'],'tie/die,ten/den,tore/door,time/dime,bat/bad','The train to Tokyo leaves at ten twenty.'],
['d','d','破裂音','D（舌先で破裂・有声）','alveolar',1,'舌先を上の歯ぐきに付けて、声を出しながら離す。','th（ð）との区別：d は歯ぐき、ð は歯の先。語末に「ド」と母音を足さない。',['date','deliver','order','need','idea'],'day/they,dough/though,den/then,dare/there,doze/those','Did you send the order date to the dealer?'],
['k','k','破裂音','K（舌の奥で破裂）','velar',0,'舌の奥を上あごの奥（軟口蓋）に付けて、息と一緒に離す。','語末の k に「ク」を足す（pick が picky に近づく）。',['call','client','copy','check','market'],'coat/goat,cap/gap,curl/girl,back/bag,cold/gold','Could you check the client list before the call?'],
['g','g','破裂音','G（舌の奥で破裂・有声）','velar',1,'k と同じ位置で、声を出しながら離す。','語中の g を鼻にかけた「ガ行鼻濁音」にしない。',['goal','give','agree','big','signal'],'goat/coat,gold/cold,glass/class,bag/back,gap/cap','The group agreed on a big goal for August.'],
['f','f','摩擦音','F（歯と唇）','labiodental',0,'上の前歯を下唇の内側に軽く乗せ、すき間から息を出し続ける。','日本語の「フ」（両唇）で代用し、h に聞こえる（fold が hold に）。',['fee','file','form','office','half'],'fold/hold,feel/heel,fat/hat,fair/hair,fall/hall','Fill in the form and send it to the office by Friday.'],
['v','v','摩擦音','V（歯と唇・有声）','labiodental',1,'f と同じ形で声を出し、唇がふるえるのを感じる。','b になりやすい（vote が boat に）。唇を閉じない。',['visit','very','review','move','survey'],'vote/boat,very/berry,van/ban,vest/best,vet/bet','We reviewed the survey results very carefully.'],
['th','θ','摩擦音','TH（無声）','dental',0,'舌先を上の前歯の先に軽く当て、そのすき間から息を出す。','s や t に置き換わる（think が sink、thank が sank）。',['think','three','thank','method','month'],'think/sink,thick/sick,thank/sank,path/pass,mouth/mouse','I think the third method is the best.'],
['dh','ð','摩擦音','TH（有声）','dental',1,'θ と同じ位置で声を出す。舌先がふるえる。','d や z に置き換わる（they が day）。舌先を歯の先まで出す。',['the','this','they','other','together'],'they/day,then/den,though/dough,breathe/breeze,there/dare','They worked together on the other project.'],
['s','s','摩擦音','S','alveolar',0,'舌先を上の歯ぐきに近づけ、細く鋭い息を出す。唇は丸めない。','日本語の「シ」は sh 寄りで、see が she に聞こえる。「スィ」と言う。',['sale','service','cost','sea','system'],'see/she,sip/ship,sell/shell,save/shave,seat/sheet','Please see the sales figures on the last sheet.'],
['z','z','摩擦音','Z（有声）','alveolar',1,'s と同じ形で声を出す。舌先はどこにも触れない。','「ヅ」のように舌先を付けてしまう。語末の z（plans）が s になる。',['zone','busy','deposit','size','reason'],'zip/sip,zoo/sue,prize/price,eyes/ice,rise/rice','The prize was a surprise for the busy team.'],
['sh','ʃ','摩擦音','SH','postalveolar',0,'舌を s より少し奥へ引き、唇を丸めて突き出して息を出す。','唇の丸めが弱く s に近づく。she と see を言い分ける。',['share','shipping','session','finish','machine'],'she/see,ship/sip,shoe/sue,shine/sign,sheet/seat','She will finish the shipping schedule this morning.'],
['zh','ʒ','摩擦音','ZH（有声）','postalveolar',1,'ʃ と同じ形で声を出す。','「ジ」と舌を付けてしまう。舌先はどこにも触れない。',['measure','usual','decision','casual','vision'],'','The usual measure was a casual decision.'],
['h','h','摩擦音','H','glottal',0,'口を次の母音の形にして、のどから息だけを出す。','who を「フー」と唇で言う（f になる）。hi と he は日本語より息を強く。',['hotel','help','hire','behind','perhaps'],'hold/fold,heel/feel,hair/fair,hat/fat,hall/fall','Could you help me hold the hotel door?'],
['ch','tʃ','破擦音','CH','postalveolar',0,'舌先を歯ぐきの少し後ろに付けてから、ʃ の形で離す。唇は丸める。','ʃ との区別：tʃ は一度舌を付ける（chip と ship）。',['check','charge','purchase','each','watch'],'chip/ship,chair/share,cheap/sheep,watch/wash,cheese/she\'s','Check each charge before you make the purchase.'],
['j','dʒ','破擦音','J（有声）','postalveolar',1,'tʃ と同じ動きで声を出す。唇を丸める。','z や「ジ」の摩擦だけになる。一度舌を付けてから離す。',['job','manager','judge','page','project'],'jeep/cheap,joke/choke,jeer/cheer,ridge/rich,junk/chunk','The manager joined the project in June.'],
['m','m','鼻音','M','bilabial',1,'唇を閉じたまま鼻から声を出す。語末でも唇を閉じ切る。','語末の m が「ン」になり n と区別がなくなる（team と teen）。',['meeting','market','amount','team','room'],'some/sun,team/teen,comb/cone,dime/dine,rum/run','The team will meet in room nine.'],
['n','n','鼻音','N','alveolar',1,'舌先を上の歯ぐきに付けたまま鼻から声を出す。語末でも舌先を付ける。','語末で舌先が離れ「ン」になる。m・ŋ と混ざる。',['name','next','plan','clean','ten'],'sun/some,teen/team,cone/comb,win/wing,thin/thing','The new plan starts next Monday.'],
['ng','ŋ','鼻音','NG','velar',1,'舌の奥を上あごの奥に付けたまま鼻から声を出して終える。','最後に「グ」を足してしまう（sing が sing-g に）。',['meeting','long','thing','bring','building'],'sing/sin,thing/thin,rang/ran,wing/win,sung/sun','Bring the long list to the morning meeting.'],
['l','l','側面音','L','alveolar',1,'舌先を上の前歯のすぐ裏の歯ぐきに押し当て、当てたまま舌の両脇から声を出す。語末の L は舌の奥も持ち上げる。','日本語のラ行（舌で一瞬はじく音）になりがち。舌を当てたまま保つ。',['light','late','collect','sale','deal'],'light/right,lead/read,long/wrong,collect/correct,glass/grass,fly/fry','Please collect the files from the lobby later.'],
['r','ɹ','接近音','R','retroflex',1,'舌先はどこにも触れない。舌先を少し奥に引いて浮かせ、唇を丸めて突き出す。「ゥラ」と唇から入る。','舌先が歯ぐきに当たるとラ行か L になる（right が light）。',['report','rate','correct','price','career'],'right/light,read/lead,wrong/long,grass/glass,fry/fly,correct/collect','The report shows the correct rate for every region.'],
['w','w','接近音','W','bilabial',1,'唇を小さく丸めて突き出してから一気に開く。','唇の丸めが弱く、ただの「ウ」になる。would や woman の w を落とさない。',['work','week','website','away','quality'],'west/vest,wine/vine,wet/vet,wail/veil,wiper/viper','We will work on the website this week.'],
['y','j','接近音','Y','palatal',1,'舌の中央を上あごに近づけ、すぐに次の母音へ移る。','year を ear のように言い、y を落とす。舌をもっと上げる。',['year','yes','use','young','beyond'],'year/ear,yeast/east,yam/am,yolk/oak,yield/eeled','Yes, you can use it for a year.'],
['ii','iː','長母音','長い i（see）','front-high',1,'口角を横に引き、舌を高く前へ。長めに。','ɪ（sit）と同じ短い「イ」にしない。',['see','team','receive','agree','key'],'seat/sit,leave/live,feel/fill,sheep/ship,beat/bit','Please leave the key with the team.'],
['i','ɪ','短母音','短い i（sit）','front-mid-high',1,'力を抜いて短く。口の開きは iː よりやや広く、エに寄る。','長い iː と区別しない（sit と seat が同じになる）。',['sit','list','fifty','business','finish'],'sit/seat,live/leave,fill/feel,ship/sheep,bit/beat','This list is for the business trip.'],
['ei','eɪ','二重母音','ay（say）','front-mid',1,'「エ」から「イ」へなめらかに移る。1拍の中で。','「エー」と伸ばして ɛ に聞こえる（late が let に）。',['sale','date','pay','train','change'],'late/let,sale/sell,pain/pen,wait/wet,taste/test','They may change the sale date.'],
['e','ɛ','短母音','短い e（bed）','front-low-mid',1,'日本語の「エ」より少し口を開けて短く。','æ（bad）と区別する。æ よりあごを上げる。',['send','test','check','rent','ahead'],'bed/bad,pen/pan,men/man,said/sad,set/sat','Send the test results to the rental desk.'],
['ae','æ','短母音','æ（cat）','front-low',1,'「エ」の口の形のまま、あごを下げて「ア」と言う。口角を横に引く。','日本語の「ア」になり cat が cut に聞こえる。',['plan','cancel','staff','manager','answer'],'cat/cut,bag/bug,hat/hut,match/much,cap/cup,ran/run','The manager had to cancel the staff plan.'],
['uh','ʌ','短母音','短い u（cut）','central-low-mid',1,'口を軽く開け、力を抜いて短い「ア」。唇は丸めない。','æ や ɑ と混ざる（cut が cat・cot に）。',['budget','customer','month','run','public'],'cut/cat,bug/bag,luck/lock,hut/hot,cup/cop','Our customers must come once a month.'],
['aa','ɑ','母音','o（hot）','back-low',1,'口を大きく縦に開け、舌を低く奥へ。','日本語の「オ」にしない（hot が「ホット」に）。',['job','stock','option','top','contract'],'hot/hut,lock/luck,cop/cup,not/nut,calm/come','The top job offer was not in stock options.'],
['aw','ɔ','母音','aw（law）','back-mid-low',1,'唇を少し丸め、口を縦に開けて奥で「オー」。地域によって ɑ と同じ音になる。','oʊ（low）と混同する（law と low）。',['law','call','cost','office','author'],'law/low,bought/boat,walk/woke,called/cold,saw/so','We called the law office about the cost.'],
['ou','oʊ','二重母音','o（go）','back-mid',1,'「オ」から唇を丸めて「ウ」へ移る。','「オー」と伸ばして ɔ に聞こえる（coat が caught に）。',['go','know','phone','hotel','program'],'boat/bought,low/law,cold/called,woke/walk,so/saw','Please phone the hotel before you go.'],
['u','ʊ','短母音','短い oo（book）','back-mid-high',1,'唇を軽く丸め、力を抜いて短く。','長い uː（fool）と区別しない。',['book','good','look','full','should'],'full/fool,pull/pool,look/Luke,soot/suit,could/cooed','You should look at this good book.'],
['uu','uː','長母音','長い oo（food）','back-high',1,'唇を強く丸めて突き出し、舌を高く奥へ。長めに。','唇の丸めが弱く日本語の「ウ」になる。',['new','schedule','move','choose','soon'],'fool/full,pool/pull,Luke/look,suit/soot,cooed/could','We will move to the new room soon.'],
['schwa','ə','弱母音','あいまい母音（about）','central',1,'口も舌も力を抜いて、短く弱く「ア」とも「ウ」ともつかない音。強勢のない音節に現れる。','つづり通りにはっきり読む（about の a を「ア」と強く）。弱くするほど英語らしくなる。',['about','support','problem','today','banana'],'','Today the company will support a new program.'],
['er','ɝ','R母音','R の響きの母音（bird）','central-mid',1,'R の舌の形（舌先を引いて浮かせる）を保ったまま母音を出す。口はあまり開けない。','「アー」と口を開けてしまう（bird が bud に）。',['work','first','purchase','early','service'],'bird/bud,hurt/hut,firm/farm,heard/hard,girl/gull','Her first purchase was early in the service.'],
['ai','aɪ','二重母音','i（time）','front-low',1,'口を大きく開けた「ア」から「イ」へ移る。','「アイ」を2拍で言う。1拍で素早く移る。',['time','price','file','online','hire'],'like/lake,mile/mail,time/tame,line/lane,fine/phone','The price is fine if we hire them online.'],
['au','aʊ','二重母音','ow（now）','front-low',1,'「ア」から唇を丸めて「ウ」へ移る。','oʊ（no）と混同する（now と no）。',['now','out','amount','account','downtown'],'now/no,found/phoned,town/tone,loud/load,couch/coach','The amount in the account is now out of date.'],
['oi','ɔɪ','二重母音','oy（boy）','back-mid-low',1,'唇を丸めた「オ」から「イ」へ移る。','「オイ」を2拍で言う。1拍で。',['choice','point','employ','avoid','join'],'boy/buy,toy/tie,oil/aisle,boil/bile,foil/file','Our choice is to avoid employing more staff.'],
];
const PH_PLACE={bilabial:[27,92,'両唇'],labiodental:[33,94,'唇と上の歯'],dental:[42,90,'歯の先'],alveolar:[55,78,'歯ぐき'],postalveolar:[70,70,'歯ぐきの後ろ'],palatal:[100,60,'硬口蓋（上あご）'],retroflex:[76,72,'舌先を引いて浮かせる'],velar:[140,70,'軟口蓋（上あごの奥）'],glottal:[166,142,'声門（のど）']};
// Vowel chart positions: [front(0)–back(1), high(0)–low(1)], diphthongs glide to the second point.
const PH_VOWEL={ii:[0,0],i:[.15,.15],ei:[.08,.32,.15,.12],e:[.12,.5],ae:[.05,.88],uh:[.62,.62],aa:[.92,.95],aw:[1,.72],ou:[1,.36,.85,.12],u:[.82,.15],uu:[1,0],schwa:[.5,.5],er:[.5,.4],ai:[.45,.95,.15,.15],au:[.45,.95,.85,.15],oi:[1,.7,.15,.15]};
const EE_PHONEMES=window.EE_PHONEMES=PH_RAW.map(r=>({key:r[0],ipa:r[1],group:r[2],name:r[3],place:r[4],voiced:!!r[5],how:r[6],trap:r[7],words:r[8],pairs:r[9]?r[9].split(',').map(x=>x.split('/')):[],sentence:r[10]}));
function phVowel(p){return !!PH_VOWEL[p.key];}
function phDiagram(p){
 if(phVowel(p)){const v=PH_VOWEL[p.key],pt=(x,y)=>{const left=30+50*y;return [left+(170-left)*x,20+110*y];};const a=pt(v[0],v[1]);let s='<svg class="phdia" viewBox="0 0 200 160" role="img" aria-label="母音図での位置"><polygon points="30,20 170,20 170,130 80,130" fill="none" stroke="currentColor" stroke-opacity=".35" stroke-width="2"/><line x1="55" y1="75" x2="170" y2="75" stroke="currentColor" stroke-opacity=".15"/><line x1="100" y1="20" x2="125" y2="130" stroke="currentColor" stroke-opacity=".15"/><g font-size="9" fill="currentColor" opacity=".7"><text x="30" y="13">前（舌が前）</text><text x="140" y="13">後ろ</text><text x="2" y="24">高</text><text x="2" y="134">低</text><text x="60" y="150">口の開き：上ほど狭く、下ほど広い</text></g>';
  EE_PHONEMES.filter(q=>PH_VOWEL[q.key]&&q.key!==p.key&&PH_VOWEL[q.key].length===2).forEach(q=>{const b=pt(PH_VOWEL[q.key][0],PH_VOWEL[q.key][1]);s+='<text x="'+b[0].toFixed(0)+'" y="'+(b[1]+4).toFixed(0)+'" font-size="10" text-anchor="middle" fill="currentColor" opacity=".35">'+q.ipa.replace('ː','')+'</text>';});
  if(v.length===4){const b=pt(v[2],v[3]);s+='<defs><marker id="pha" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M0 0 10 5 0 10z" fill="#FF0033"/></marker></defs><line x1="'+a[0]+'" y1="'+a[1]+'" x2="'+b[0]+'" y2="'+b[1]+'" stroke="#FF0033" stroke-width="3" marker-end="url(#pha)"/>';}
  return s+'<circle cx="'+a[0]+'" cy="'+a[1]+'" r="9" fill="#FF0033"/><text x="'+a[0]+'" y="'+(a[1]+4)+'" font-size="11" font-weight="700" text-anchor="middle" fill="#fff">'+p.ipa.replace('ː','').slice(0,2)+'</text></svg>';}
 const pl=PH_PLACE[p.place]||PH_PLACE.alveolar,nasal=p.group==='鼻音';
 return '<svg class="phdia" viewBox="0 0 200 160" role="img" aria-label="調音の位置：'+pl[2]+'"><path d="M60 10Q20 10 18 50L8 66Q6 72 16 74L22 76Q18 80 22 84Q16 88 24 96L24 104Q26 118 40 120L60 122Q64 150 90 158" fill="none" stroke="currentColor" stroke-opacity=".55" stroke-width="2.5"/><path d="M52 76Q60 70 70 68Q100 50 138 60Q152 64 158 78Q160 88 154 92" fill="none" stroke="currentColor" stroke-opacity=".55" stroke-width="2.5"/><path d="M36 80h8v6h-8zM36 96h8v-6h-8z" fill="currentColor" fill-opacity=".35"/><path d="M172 70V150" stroke="currentColor" stroke-opacity=".45" stroke-width="2.5"/><path d="M44 98Q70 80 110 78Q150 80 156 110Q158 130 162 150" fill="currentColor" fill-opacity=".12" stroke="#E0648A" stroke-width="3"/>'+(nasal?'<path d="M150 58Q120 30 60 30Q40 30 30 50" fill="none" stroke="#3EA6FF" stroke-width="2.5" stroke-dasharray="5 4"/><text x="70" y="26" font-size="9" fill="#3EA6FF">息は鼻へ</text>':'')+(p.voiced?'<g stroke="#F2C230" stroke-width="2" fill="none"><path d="M178 136q4 4 0 8q-4 4 0 8"/><path d="M184 134q4 5 0 10q-4 5 0 10"/></g><text x="150" y="130" font-size="9" fill="#C8961E">声あり</text>':'<text x="146" y="130" font-size="9" fill="currentColor" opacity=".7">息だけ</text>')+'<circle cx="'+pl[0]+'" cy="'+pl[1]+'" r="8" fill="none" stroke="#FF0033" stroke-width="3"/><circle cx="'+pl[0]+'" cy="'+pl[1]+'" r="3" fill="#FF0033"/><text x="4" y="156" font-size="9" text-anchor="start" fill="currentColor" opacity=".8">口の横断面・赤丸＝'+pl[2]+'</text></svg>';}
// Phoneme lessons in the video catalog.
EE_PHONEMES.forEach((p,i)=>{const sc=['paper|mouth|ear','stage|mic|mouth','library|mouth|headphones','dusk|ear|mouth','office|mouth|check'][i%5];VC.push({id:'phon-'+p.key,g:'learning',t:'/'+p.ipa+'/ '+p.name+' · 音素チェック',kind:'speak',level:'音の基礎',phoneme:p.key,defaultMode:'phoneme',pairs:p.pairs.length>=4?p.pairs:undefined,sl:[...p.words.map(w=>[sc,w,p.name+' の例：'+w]),[sc,p.sentence,'/'+p.ipa+'/ を含む文。お手本のあとに続けて言ってみましょう。']],qs:[]});});
VMODES.phoneme='音素チェック';
let PHS=lsGet('ee-phon',{});
function phSave(key,patch){PHS[key]={...(PHS[key]||{}),...patch,at:Date.now()};lsSet('ee-phon',PHS);}
function phStatus(key){const r=PHS[key]||{};return r.said>=3?'ok':r.said||r.tried?'part':'';}
// Word check with the browser's speech recognizer: it recognizes words, not sounds, so it can only tell
// "heard as the target word" / "heard as the contrast word" / other.
const PH_SR=typeof window!=='undefined'&&(window.SpeechRecognition||window.webkitSpeechRecognition);
function phListen(){return new Promise((res,rej)=>{if(!PH_SR){rej(new Error('unsupported'));return;}const r=new PH_SR();r.lang='en-US';r.maxAlternatives=5;r.interimResults=false;let done=false;r.onresult=e=>{done=true;res([...e.results[0]].map(a=>String(a.transcript).toLowerCase().replace(/[^a-z' ]/g,' ').trim()));};r.onerror=e=>{done=true;rej(new Error(e.error||'error'));};r.onend=()=>{if(!done)res([]);};try{r.start();}catch(e){rej(e);}setTimeout(()=>{try{r.stop();}catch(e){}},4000);});}
function phJudge(alts,target,contrast){const has=(a,w)=>(' '+a+' ').includes(' '+w.toLowerCase()+' ');if(alts.some(a=>has(a,target)))return ['ok','「'+target+'」と認識されました。'];if(contrast&&alts.some(a=>has(a,contrast)))return ['ng','「'+contrast+'」に聞こえたようです。下の口の形を確認して、もう一度。'];return ['unk',alts.length?'「'+alts[0]+'」と認識されました（判定できません）。単語をはっきり1回だけ言ってみてください。':'聞き取れませんでした。マイクの許可と音量を確認してください。'];}
let PHREC=null;
async function phRecord(btn,out){if(PHREC){PHREC.stop();return;}if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==='undefined'){out.textContent='この端末・ブラウザーでは録音できません。';return;}let stream;try{stream=await navigator.mediaDevices.getUserMedia({audio:true});}catch(e){out.textContent='マイクを使えませんでした（許可を確認してください）。';return;}const rec=new MediaRecorder(stream),chunks=[];PHREC=rec;btn.textContent='■ 停止';rec.ondataavailable=e=>chunks.push(e.data);rec.onstop=()=>{PHREC=null;stream.getTracks().forEach(t=>t.stop());btn.textContent='● 録音';const url=URL.createObjectURL(new Blob(chunks,{type:rec.mimeType}));out.innerHTML='<audio controls src="'+url+'"></audio><span class="muted small">自分の声を聞いたら、上のお手本と比べてください。録音は端末の中だけで使い、保存・送信しません。</span>';};rec.start();setTimeout(()=>{if(rec.state==='recording')rec.stop();},6000);}
function vPhoneme(){const l=V.lesson,p=EE_PHONEMES.find(x=>x.key===l.phoneme),box=$('#vActivity');if(!p||!box)return;const st=PHS[p.key]||{},pairs=p.pairs.length?p.pairs:p.words.map(w=>[w,'']);const k=Math.min(st.next||0,pairs.length-1);const pair=pairs[k];
 box.innerHTML='<div class="phcard"><div class="phhead"><span class="phipa">/'+esc(p.ipa)+'/</span><div><b>'+esc(p.name)+'</b><small>'+esc(p.group)+' · '+(phVowel(p)?'母音':(p.voiced?'有声（のどがふるえる）':'無声（息だけ）'))+'</small></div></div><div class="phgrid">'+phDiagram(p)+'<div><h4>口の作り方</h4><p>'+esc(p.how)+'</p><h4>⚠️ つまずきポイント</h4><p>'+esc(p.trap)+'</p></div></div></div>'
 +'<div class="phcard"><h4>① お手本を聞く</h4><div class="row">'+p.words.map(w=>'<button class="btn sm say" data-say="'+esc(w)+'">'+esc(w)+'</button>').join('')+'<button class="btn sm say" data-say="'+esc(p.words.join(', '))+'" data-rate="0.7">ゆっくり全部</button></div>'+(p.pairs.length?'<p class="small muted">違いに注意：'+p.pairs.slice(0,4).map(x=>'<button class="phpair say" data-say="'+esc(x[0]+'. '+x[1])+'">'+esc(x[0])+' / '+esc(x[1])+'</button>').join(' ')+'</p>':'')+'</div>'
 +'<div class="phcard"><h4>② 言ってみる（単語チェック '+(k+1)+' / '+pairs.length+'）</h4><p class="phtarget">'+esc(pair[0])+(pair[1]?'<small>（'+esc(pair[1])+' にならないように）</small>':'')+'</p><div class="row"><button class="btn sm say" data-say="'+esc(pair[0])+'">お手本</button><button class="btn primary" id="phSay"'+(PH_SR?'':' disabled')+'>🎤 言う</button><button class="btn sm" id="phNext">次の単語</button></div><p id="phOut" role="status" class="phout">'+(PH_SR?'':'この端末・ブラウザーは音声認識に対応していません（Chrome・Edge・Safari で使えます）。③の録音で確認してください。')+'</p><p class="small muted">音声認識は「単語として何に聞こえたか」を返すだけで、音素の正確さの採点ではありません。音素ごとの点数は発音コーチで確認できます。</p></div>'
 +'<div class="phcard"><h4>③ 録音してお手本と比べる</h4><div class="row"><button class="btn" id="phRec">● 録音</button><button class="btn sm say" data-say="'+esc(p.sentence)+'">文のお手本</button></div><p class="phsent">'+esc(p.sentence)+'</p><div id="phRecOut" class="phout"></div></div>'
 +'<div class="phcard"><h4>④ 音素ごとに採点する</h4><p class="small">発音コーチ（wav2vec2 の音素認識）で、この文の各音素を採点し、/'+esc(p.ipa)+'/ が何の音に聞こえたかを確認します。</p><a class="btn primary" target="_blank" rel="noopener" href="'+esc(coachURL(p.sentence,[p.sentence,...p.words]))+'">発音コーチで録音</a>'+(p.pairs.length?' <button class="btn" data-vmode2="hvpt">聞き分けテストへ</button>':'')+'</div>';
 const out=$('#phOut');$('#phNext').onclick=()=>{phSave(p.key,{next:(k+1)%pairs.length});vPhoneme();};
 $('#phSay').onclick=async()=>{const b=$('#phSay');b.disabled=true;b.textContent='🎤 聞いています…';stopSpeech();try{const alts=await phListen();const [cls,msg]=phJudge(alts,pair[0],pair[1]);out.className='phout '+cls;out.textContent=(cls==='ok'?'✅ ':cls==='ng'?'❌ ':'')+msg;const said=(PHS[p.key]?.said||0)+(cls==='ok'?1:0);phSave(p.key,{tried:1,said,...(cls==='ok'?{next:(k+1)%pairs.length}:{})});if(cls!=='unk')videoMistake('phon-'+p.key+'-'+pair[0],'/'+p.ipa+'/ '+pair[0]+(pair[1]?' （'+pair[1]+' と区別）':''),pair[0],l.id,'音素チェック',cls==='ok');}catch(e){out.className='phout unk';out.textContent=e.message==='not-allowed'?'マイクが許可されていません。ブラウザーの設定で許可してください。':'音声認識を使えませんでした（'+e.message+'）。';}b.disabled=false;b.textContent='🎤 言う';};
 $('#phRec').onclick=()=>phRecord($('#phRec'),$('#phRecOut'));
 box.querySelectorAll('[data-vmode2]').forEach(b=>b.onclick=()=>{V.mode='hvpt';V.hp=0;V.hpHeard=false;V.hpDone=false;vActivity();});}
// Chart of all phonemes: a home chip and its own page (the watch page's 音素チェック button opens it).
function phChartHTML(){const groups=[['子音',EE_PHONEMES.filter(p=>!phVowel(p))],['母音',EE_PHONEMES.filter(phVowel)]];const done=EE_PHONEMES.filter(p=>phStatus(p.key)==='ok').length;
 return '<div class="phintro"><h2>音素チェック · 全'+EE_PHONEMES.length+'音</h2><p class="small">一般米語の子音'+groups[0][1].length+'・母音'+groups[1][1].length+'（あいまい母音を含む）。音をえらぶと、口の形の図、日本語話者のつまずき、お手本、単語チェック（音声認識）、録音比較、聞き分けテストに進めます。</p><p class="small"><b>'+done+'</b> / '+EE_PHONEMES.length+' 音で単語チェックを3回以上クリア</p></div>'
 +groups.map(([g,list])=>'<h3 class="phgh">'+g+'</h3><div class="phchart">'+list.map(p=>'<button class="phtile '+phStatus(p.key)+'" data-video="phon-'+p.key+'"><span class="phipa">/'+esc(p.ipa)+'/</span><span class="phw">'+esc(p.words[0])+'</span><small>'+esc(p.group)+'</small></button>').join('')+'</div>').join('');}
const phSection=document.createElement('section');phSection.id='p-phonemes';phSection.hidden=true;phSection.setAttribute('role','tabpanel');$('#p-home').parentNode.appendChild(phSection);TABS.push('phonemes');NAVOF.phonemes='home';
const oldShowTabPh=showTab;showTab=function(t,noHist){oldShowTabPh(t,noHist);if(t==='phonemes')phSection.innerHTML=phChartHTML();};
if(!HCHIPS.some(c=>c[0]==='phonemes'))HCHIPS.splice(HCHIPS.findIndex(c=>c[0]==='speak')+1,0,['phonemes','音素']);
const oldRenderHomePh=renderHome;renderHome=function(){if(homeChip!=='phonemes')return oldRenderHomePh();$('#homeChips').innerHTML=HCHIPS.map(c=>'<button data-hchip="'+c[0]+'" aria-pressed="'+(homeChip===c[0])+'">'+c[1]+'</button>').join('');$('#homeBody').innerHTML=phChartHTML();};
