const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync('docs/index.html','utf8');
const ctx={console,Math,S:{settings:{main:{rate:.7,voice:'old',targetScore:850}}},window:{},renderVoiceSelect(){}};
vm.createContext(ctx);vm.runInContext(fs.readFileSync('speech-profile.js','utf8'),ctx);
vm.runInContext(html.slice(html.indexOf('function settings(){'),html.indexOf('function saveSettings(')),ctx);
vm.runInContext(html.slice(html.indexOf('let voices=[];'),html.indexOf('let playTok=')),ctx);
const voice=(name,lang)=>({name,lang,voiceURI:name});
ctx.samples=[voice('Microsoft David','en-US'),voice('Microsoft Aria Natural','en-US'),voice('Daniel','en-GB'),voice('Serena','en-GB'),voice('Liam','en-CA'),voice('Clara','en-CA'),voice('William','en-AU'),voice('Karen','en-AU'),voice('Gordon','en-NZ'),voice('Natasha','en-NZ'),voice('Google English','en-IN')];
const run=s=>vm.runInContext(s,ctx);
assert.equal(run('settings().rate'),1);assert.equal(run('settings().voice'),'');assert.equal(run('settings().accent'),'mixed');assert.equal(run('settings().gender'),'mixed');assert.equal(run('settings().targetScore'),850);
run("S.settings.main={rate:.8,voice:'custom',accent:'en-GB',gender:'female',speechProfileVersion:2}");assert.equal(run('settings().rate'),.8);assert.equal(run('settings().voice'),'custom');
assert.equal(run("EESpeech.pick(samples,{accent:'en-US',gender:'male'}).name"),'Microsoft David');
assert.equal(run("EESpeech.pick(samples,{accent:'en-US',gender:'female'}).name"),'Microsoft Aria Natural');
assert.equal(run("EESpeech.gender({name:'English Female'})"),'female');assert.equal(run("EESpeech.gender({name:'Google US English'})"),'unknown');
assert.equal(run("EESpeech.pick([])"),null);
assert.ok(run("EESpeech.pick(samples,{accent:'en-IE',gender:'male'})"));
assert.equal(run("EESpeech.pick(samples,{voice:'Daniel'}).name"),'Daniel');
const chosen=run("Array.from({length:100},(_,i)=>EESpeech.pick(samples,{accent:'mixed',gender:'mixed',seed:'video-'+i}))");
assert.ok(new Set(chosen.map(v=>v.lang)).size>=4);assert.ok(chosen.every(v=>v.lang!=='en-IN'));
assert.ok(chosen.some(v=>run(`EESpeech.gender({name:${JSON.stringify(v.name)}})`)==='female'));
assert.ok(chosen.some(v=>run(`EESpeech.gender({name:${JSON.stringify(v.name)}})`)==='male'));
run("voices=samples;curTab='watch';V={lesson:{id:'video-12'}};S.settings.main={speechProfileVersion:2}");
const first=run('pickVoice().name');for(let i=0;i<5;i++)assert.equal(run('pickVoice().name'),first);
assert.equal(run("EESpeech.gender(voiceFor('M'))"),'male');assert.equal(run("EESpeech.gender(voiceFor('F'))"),'female');
assert.equal(run("voiceFor('M').lang"),run("voiceFor('F').lang"));
run("curTab='shorts';SP={it:{s:{id:'short-1'}}}");assert.equal(run('speechSeed()'),'short-1');
run("curTab='lab';LAB={id:'lesson-2'}");assert.equal(run('speechSeed()'),'lesson-2');
for(const m of html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g))new vm.Script(m[1]);
assert.equal(html,fs.readFileSync('english-express.html','utf8'));
const coach=fs.readFileSync('app.py','utf8');assert.ok(coach.includes('speech-profile.js'));assert.ok(coach.includes("accent: 'mixed', gender: 'mixed', seed: t"));
console.log('PASS: automatic video voices, stable replay, TOEIC regions, male/female roles, fallbacks, settings migration and built scripts');

