/* Fixed-content video lessons. Everything stays in the existing local store. */
const VC=[];
const VWORDS=EE_CARDS.filter(c=>/^phrase-v[23]-/.test(String(c[0])));
const VSCENES={daily:'day|chat|sun',travel:'city|train|pin',space:'space|rocket|moon',science:'paper|bulb|magnifier',tech:'night|laptop',food:'paper|bowl',music:'night|note',math:'paper|chart',animal:'forest|bird|tree',history:'paper|scroll',film:'night|film',sport:'day|ball',environment:'forest|tree|sun',work:'city|building|clock',learning:'paper|book|bulb',art:'paper|palette',words:'paper|book',money:'paper|coin|chart',dino:'forest|trex',nyc:'city|skyline',serial:'night|book'};
const VMODES={cloze:'穴埋め',build:'組み立て',speed:'速聴',questions:'設問',recall:'想起',phrases:'フレーズ',chunks:'塊',read:'速読',script:'スクリプト',pron:'発音チェック',hvpt:'聞き分け',fluency:'4 / 3 / 2'};
EE_LONG.forEach(s=>VC.push({...s,defaultMode:'questions'}));
const VDECK_T=['旅先で伝える','仕事の段取り','連絡と依頼','予定と対応','会話をつなぐ','行動を説明する','条件を伝える','意見を組み立てる','比較して考える','案内を読み解く','手続きと買い物','職場の書類','根拠と判断','協力して進める','話し合いの表現'];
const VDECK_SC=['paper|book|chat'];
function vDeck(id,t,level,cards,sc){VC.push({id,g:'words',t:t+' · '+cards.length+'フレーズ',kind:'practice',level,cards,defaultMode:'phrases',sl:cards.map(c=>[sc,c[3],c[4]]),qs:[]});}
{const v2=VWORDS.filter(c=>c[0].startsWith('phrase-v2-')),v3=VWORDS.filter(c=>c[0].startsWith('phrase-v3-'));
for(let i=0;i<v2.length;i+=8)vDeck('deck-'+i,VDECK_T[i/8]||'フレーズ セット'+(i/8+1),i<48?'A2–B1':'B1–B2',v2.slice(i,i+8),'paper|book|chat');
const byId=new Map(v3.map(c=>[c[0],c]));(window.EE_DECKS||[]).forEach(d=>{const cards=d.cards.map(id=>byId.get(id)).filter(Boolean);if(cards.length)vDeck(d.id,d.t,d.level,cards,d.sc||VDECK_SC[0]);});}
EE_MICRO.forEach(m=>{const s=EE_SHORTS.find(s=>s.microId===m.id);if(s)VC.push({id:'recall-'+m.id,g:s.g,t:m.title+' · 思い出して話す',kind:'practice',level:'A2–B1',sl:s.sl.slice(0,-1),defaultMode:'recall',qs:[],microId:m.id});});
EE_PAIRS.forEach(p=>{for(let i=0;i<p.pairs.length;i+=(p.pairs.length-i<10?p.pairs.length:6)){const pairs=p.pairs.slice(i, p.pairs.length-i<10?p.pairs.length:i+6);VC.push({id:'contrast-'+p.id+'-'+i,g:'learning',t:p.name+' · 聞き分けセット '+(i/6+1),kind:'speak',level:'音の基礎',pairs,defaultMode:'hvpt',sl:pairs.map(pair=>['night|wave|book',pair.join('. '),'音の違いを聞いてから、下の「聞き分け」で確認しましょう。']),qs:[]});}});
if(typeof normPassage==='function')EE_PASSAGES.map(normPassage).forEach(p=>VC.push({id:'passage-'+p.id,g:p.id==='bp4'?'money':'nyc',t:p.title,kind:'listen',level:'B1',defaultMode:'questions',sl:p.sents.map(x=>[PSCENE[p.id]||'city|skyline',(x.sp?x.sp+': ':'')+sentText(x),sentJa(x)]),qs:p.qs.map(q=>[q.q,q.c,q.a])}));
EE_LONG.forEach(s=>VC.push({...s,id:'talk-'+s.id,t:s.t+' · 4 / 3 / 2',kind:'speak',defaultMode:'fluency'}));
// New short episodes retain a direct pointer to their complete lesson.
EE_LONG.forEach(s=>(s.paragraphs||s.sl).forEach((sl,i)=>EE_SHORTS.push({id:'episode-'+s.id+'-'+i,g:s.g,t:s.t+' · '+(i+1),sl:(()=>{const en=sl[1].split(/(?<=[.!?])\s+/),ja=sl[2].match(/[^。]+。?/g)||[];return en.length===ja.length?en.map((e,j)=>[sl[0],e,ja[j]]):[sl];})(),w:[],q:null,videoId:s.id})));
const V={lesson:null,slide:0,mode:'script',playing:false,token:0,rate:1,phrase:0,revealed:false,hp:0,hpHeard:false,hpDone:false,hpToken:0,hpOrder:[],readAt:0,readDone:0,answers:{}};
const videoSection=document.createElement('section');videoSection.id='p-watch';videoSection.hidden=true;videoSection.setAttribute('role','tabpanel');$('#p-home').parentNode.appendChild(videoSection);TABS.push('watch');NAVOF.watch='home';
function videoMistake(key,prompt,answer,lessonId,kind,ok=false){const rows={...(S.meta.videoMistakes?.rows||{})};if(ok){if(rows[key])rows[key]={...rows[key],resolved:true,at:Date.now()};}else rows[key]={prompt,answer,lessonId,kind,at:Date.now(),resolved:false};const sorted=Object.entries(rows).sort((a,b)=>b[1].at-a[1].at).slice(0,200);put('meta','videoMistakes',{rows:Object.fromEntries(sorted)});}
function vStop(){V.token++;V.playing=false;stopSpeech();if($('#vPlay'))$('#vPlay').textContent='▶ 再生';}
const oldShowTabV=showTab;
showTab=function(t,noHist){vStop();if(curTab==='watch'){labLeave();V.hpToken++;$('#labBody').replaceChildren();$('#vFluencyBody')?.replaceChildren();}oldShowTabV(t,noHist);if(t==='stats:settings')vShowSettings();document.body.classList.toggle('ee-shorts-full',t==='shorts'&&matchMedia('(max-width:719px)').matches);if(t==='shorts')sizeShorts();if(t==='watch')renderWatch();};
function openVideo(id,mode){let l=VC.find(x=>x.id===id);if(!l){const s=shortsAll().find(x=>x.id===id);if(s){l={...s,kind:'listen',level:'読み聞き',qs:vShortQs(s),defaultMode:'questions'};VC.push(l);}}if(!l)return;labLeave();V.lesson=l;V.slide=0;V.mode=mode||l.defaultMode||'script';V.phrase=0;V.revealed=false;V.hp=0;V.hpHeard=false;V.hpDone=false;V.hpOrder=(l.pairs||[]).map(()=>Math.random()<.5?0:1);V.answers={};V.readAt=0;V.readDone=0;showTab('watch');}
function vWords(l){return l.sl.map(s=>s[1].replace(/\//g,' ')).join(' ').trim().split(/\s+/).length;}
const VAVI={daily:'chat',travel:'globe',space:'moon',science:'atom',tech:'laptop',food:'bowl',music:'note',math:'chart',animal:'bird',history:'scroll',film:'film',sport:'ball',environment:'tree',work:'building',learning:'bulb',art:'palette',words:'book',money:'coin',dino:'trex',nyc:'skyline',serial:'magnifier'};
const VICON={};
function vIcon(k){if(VICON[k])return VICON[k];const d=ART.shape?ART.shape(k):'';if(!d)return '';let b={x:-50,y:-50,width:100,height:100};try{const t=document.createElementNS('http://www.w3.org/2000/svg','svg');t.setAttribute('style','position:absolute;width:0;height:0;visibility:hidden');t.innerHTML='<g>'+d+'</g>';document.body.appendChild(t);const r=t.firstChild.getBBox();t.remove();if(r.width&&r.height)b=r;}catch(e){}const m=Math.max(b.width,b.height)*1.5,cx=b.x+b.width/2,cy=b.y+b.height/2;return VICON[k]='<svg viewBox="'+(cx-m/2).toFixed(1)+' '+(cy-m/2).toFixed(1)+' '+m.toFixed(1)+' '+m.toFixed(1)+'" aria-hidden="true">'+d+'</svg>';}
function vAvatarIcon(item,color){return '<span class="av vav" style="--c:'+esc(color||'#4a5568')+'" aria-hidden="true">'+vIcon(item)+'</span>';}
function vAvatar(g){return vAvatarIcon(VAVI[g]||'book',(typeof GCOL!=='undefined'&&GCOL[g])||'#4a5568');}
function vSceneItem(sc){return String(sc||'').split('|').slice(1).find(k=>ART.names.includes(k))||'book';}
function vCard(l){return '<button class="vcard" data-video="'+esc(l.id)+'"><div class="th">'+ART.draw(l.sl[0][0]).replace('viewBox="0 0 300 380"','viewBox="0 100 300 169"')+'<span class="vkind">'+esc(VMODES[l.defaultMode]||'聞く・読む')+'</span><span class="dur">'+(l.defaultMode==='fluency'?'4 + 3 + 2分':l.cards?l.cards.length+'フレーズ':l.pairs?l.pairs.length+'問':vWords(l)+'語')+'</span></div><div class="meta">'+vAvatar(l.g)+'<div><div class="vt">'+esc(l.t)+'</div><div class="vm">'+esc(EE_GENRES[l.g]||'英語')+' · '+esc(l.level)+'目安</div></div></div></button>';}
// Replace letter avatars on the older cards with drawn icons.
const oldVcardHTMLV=vcardHTML;vcardHTML=function(f){return oldVcardHTMLV(f).replace(/<div class="av" style="background:([^"]+)">[^<]*<\/div>/,(_,c)=>vAvatarIcon(vSceneItem(f.sc),c));};
const oldSongCardV=songCardHTML;songCardHTML=function(x){return oldSongCardV(x).replace(/<div class="av" style="background:([^"]+)">[^<]*<\/div>/,(_,c)=>vAvatarIcon('note',c));};
const oldPassageCardV=passageCardHTML;passageCardHTML=function(p){return oldPassageCardV(p).replace(/<div class="av" style="background:([^"]+)">[^<]*<\/div>/,(_,c)=>vAvatarIcon(vSceneItem(PSCENE[p.id]||'paper|scroll'),c));};
let vLayout=lsGet('ee-home-layout-v2',{seed:0,sort:'mix'});
function vHash(s){let n=2166136261;for(const c of s)n=Math.imul(n^c.charCodeAt(0),16777619);return n>>>0;}
renderHome=function(){
 $('#homeChips').innerHTML=HCHIPS.map(c=>'<button data-hchip="'+c[0]+'" aria-pressed="'+(homeChip===c[0])+'">'+c[1]+'</button>').join('');
 let h='<div class="vtoolbar"><span>今日の動画教材</span><label>並び <select id="vSort"><option value="mix">おすすめを混ぜる</option><option value="topic">分野順</option><option value="level">難易度順</option></select></label><button class="btn sm" id="vRefresh">↻ 内容を入れ替え</button></div>';
 if(homeChip==='shorts')Object.keys(EE_GENRES).forEach(g=>h+=shelfHTML(EE_GENRES[g],shortsAll().filter(s=>s.g===g)));
 else if(homeChip==='music')h+='<div class="vgrid">'+songsAll().map(songCardHTML).join('')+'</div>';
 else {let list=VC.filter(l=>homeChip==='all'||homeChip==='materials'||l.kind===homeChip);
 list=list.slice().sort((a,b)=>vLayout.sort==='topic'?Object.keys(EE_GENRES).indexOf(a.g)-Object.keys(EE_GENRES).indexOf(b.g):vLayout.sort==='level'?a.level.localeCompare(b.level):vHash(a.id+vLayout.seed)-vHash(b.id+vLayout.seed));
 // Keep the first row balanced: a story, phrase deck, and recall episode.
 if(homeChip==='all'&&vLayout.sort==='mix'){const lead=[EE_LONG[vLayout.seed%EE_LONG.length].id,'deck-'+((vLayout.seed%15)*8),'recall-'+EE_MICRO[vLayout.seed%EE_MICRO.length].id];list=lead.map(id=>list.find(x=>x.id===id)).filter(Boolean).concat(list.filter(x=>!lead.includes(x.id)));}
 h+='<div class="vgrid">'+list.slice(0,6).map(vCard).join('')+'</div>';if(homeChip==='all')h+=shelfHTML('ショート · 知る、聞く、思い出す',recommendShorts(18));h+='<div class="vgrid">'+list.slice(6).map(vCard).join('')+'</div>';
 }$('#homeBody').innerHTML=h;$('#vSort').value=vLayout.sort;$('#vSort').onchange=e=>{vLayout.sort=e.target.value;lsSet('ee-home-layout-v2',vLayout);renderHome();};$('#vRefresh').onclick=()=>{vLayout.seed++;lsSet('ee-home-layout-v2',vLayout);renderHome();};
};
function renderWatch(){const l=V.lesson;if(!l){showTab('home');return;}videoSection.innerHTML='<div class="vwatch"><div class="vmain"><div class="vplayer" data-cc="'+V.cc+'"><div id="vScene"></div><div id="vCaption"></div></div><div class="vcontrols"><button class="btn sm" id="vPrev" aria-label="前の場面">‹</button><button class="btn sm primary" id="vPlay">▶ 再生</button><button class="btn sm" id="vNext" aria-label="次の場面">›</button><span id="vPosition"></span><input id="vSeek" aria-label="場面を移動" type="range" min="0" max="'+(l.sl.length-1)+'" value="'+V.slide+'"><button class="btn sm" id="vCC" aria-label="字幕の切り替え"></button><select id="vRate" aria-label="再生速度"><option value="0.8">0.8倍</option><option value="1">1倍</option><option value="1.2">1.2倍</option></select></div><h1 class="vtitle">'+esc(l.t)+'</h1><p class="muted small">'+esc(EE_GENRES[l.g]||'英語')+' · '+vWords(l)+'語 · '+esc(l.level)+'目安（編集上の目安） · 音声は端末の読み上げ</p><div class="vtabs" id="vTabs"></div><div id="vActivity" class="stack"></div></div><aside><h3>次の動画教材</h3>'+VC.filter(x=>x.id!==l.id&&x.kind===l.kind).slice(0,5).map(vCard).join('')+'</aside></div>';
 $('#vPlay').onclick=()=>V.playing?vStop():vPlay();$('#vPrev').onclick=()=>{vStop();V.slide=Math.max(0,V.slide-1);vDraw();};$('#vNext').onclick=()=>{vStop();V.slide=Math.min(l.sl.length-1,V.slide+1);vDraw();};$('#vSeek').oninput=e=>{vStop();V.slide=+e.target.value;vDraw();};vCCLabel();$('#vCC').onclick=()=>{V.cc=VCC[(VCC.indexOf(V.cc)+1)%VCC.length];lsSet('ee-vcc',V.cc);$('.vplayer').dataset.cc=V.cc;vCCLabel();};$('#vRate').value=V.rate;$('#vRate').onchange=e=>{const was=V.playing;vStop();V.rate=+e.target.value;if(was)vPlay();};vDraw();vActivity();}
const VCC=['both','en','off'];V.cc=lsGet('ee-vcc','both');if(!VCC.includes(V.cc))V.cc='both';
function vCCLabel(){if($('#vCC'))$('#vCC').textContent={both:'CC 英+日',en:'CC 英',off:'CC オフ'}[V.cc];}
function vDraw(){const s=V.lesson.sl[V.slide];const art=ART.draw(s[0]);$('#vScene').innerHTML='<div class="vbg">'+art+'</div><div class="vfg">'+ART.draw(s[0]).replace('viewBox="0 0 300 380"','viewBox="0 30 300 350"')+'</div>';$('#vCaption').innerHTML='<div>'+esc(s[1].replace(/\//g,' '))+'</div><small>'+esc(s[2]||'')+'</small>';$('#vPosition').textContent=(V.slide+1)+' / '+V.lesson.sl.length;$('#vSeek').value=V.slide;$('#vPrev').disabled=V.slide===0;$('#vNext').disabled=V.slide===V.lesson.sl.length-1;if(['recall','pron'].includes(V.mode)&&$('#vActivity'))vActivity();vCaptionUpdate();}
async function vPlay(){vStop();const token=V.token;V.playing=true;$('#vPlay').textContent='❚❚ 一時停止';for(let i=V.slide;i<V.lesson.sl.length;i++){if(token!==V.token||curTab!=='watch')return;V.slide=i;vDraw();await speak(V.lesson.sl[i][1].replace(/\//g,' '),V.rate,null,true);if(token!==V.token)return;if(SPEAKERR){vStop();toast('音声を再生できません。再生ボタンを押し直してください。');return;}await new Promise(r=>setTimeout(r,450));}if(token===V.token){V.playing=false;$('#vPlay').textContent='↻ もう一度';V.slide=0;}}
function vActivity(){const l=V.lesson,box=$('#vActivity');if(!box)return;let modes=['questions','recall','chunks','read','speed','script','pron'];if(l.practiceCard)modes.unshift(l.defaultMode);if(l.cards)modes.unshift('phrases');if(l.pairs)modes.unshift('hvpt');if(l.id.startsWith('long-')||l.id.startsWith('talk-'))modes.push('fluency');if(!modes.includes(V.mode))V.mode='script';$('#vTabs').innerHTML=modes.map(m=>'<button class="btn sm '+(m===V.mode?'primary':'')+'" data-vmode="'+m+'">'+VMODES[m]+'</button>').join('');$$('[data-vmode]').forEach(b=>b.onclick=()=>{vStop();V.hpToken++;if(V.mode==='fluency'){labLeave();$('#labBody').replaceChildren();}V.mode=b.dataset.vmode;vActivity();});
 if(V.mode==='script'){box.innerHTML=l.sl.map((s,i)=>'<article class="vtranscript"><button class="btn sm" data-vjump="'+i+'">▶ '+(i+1)+'</button><p>'+esc(s[1].replace(/\//g,' '))+'</p><p class="muted jp">'+esc(s[2]||'')+'</p></article>').join('');$$('[data-vjump]',box).forEach(b=>b.onclick=()=>{vStop();V.slide=+b.dataset.vjump;vDraw();vPlay();});}
 if(V.mode==='questions'){box.innerHTML=l.qs?.length?l.qs.map((q,i)=>'<fieldset class="vquestion"><legend>'+esc(q[0])+'</legend>'+q[1].map((a,j)=>'<button class="btn" data-vanswer="'+i+':'+j+'" '+(V.answers[i]!==undefined?'disabled':'')+'>'+esc(a)+'</button>').join('')+'<p id="vq'+i+'" role="status">'+(V.answers[i]!==undefined?(V.answers[i]===q[2]?'正解':'もう一度確認')+' · '+esc(q[1][q[2]]):'')+'</p></fieldset>').join(''):'<p>この教材は想起練習が中心です。要点を英語で言ってから、原文と比べてください。</p><button class="btn" id="vToRecall">想起を始める</button>';if($('#vToRecall'))$('#vToRecall').onclick=()=>{V.mode='recall';vActivity();};$$('[data-vanswer]',box).forEach(b=>b.onclick=()=>{const [i,j]=b.dataset.vanswer.split(':').map(Number);if(V.answers[i]!==undefined)return;V.answers[i]=j;const q=l.qs[i];videoMistake(l.id+'-q'+i,q[0],q[1][q[2]],l.id,'設問',j===q[2]);bump({compTot:1,compOk:j===q[2]?1:0});vActivity();});}
 if(V.mode==='recall'){box.innerHTML='<h3>原文を隠して、今の場面を説明する</h3><p>'+esc(l.sl[V.slide][2]||l.t)+'</p><textarea id="vRecallText" aria-label="思い出した英語" placeholder="声に出してから、必要ならメモ"></textarea><details><summary>原文を見て比べる</summary><p>'+esc(l.sl[V.slide][1])+'</p><button class="btn" data-vremember="0">思い出せなかった</button> <button class="btn" data-vremember="1">思い出せた</button></details>';$$('[data-vremember]',box).forEach(b=>b.onclick=()=>{videoMistake(l.id+'-recall-'+V.slide,l.sl[V.slide][2],l.sl[V.slide][1],l.id,'想起',b.dataset.vremember==='1');b.disabled=true;toast('記録しました');});}
 if(V.mode==='chunks'){box.innerHTML='<h3>意味のまとまりで、前から理解する</h3><p class="muted small">区切りは読みやすさを助ける目安です。</p>'+l.sl.map(s=>'<article class="vtranscript">'+s[1].replace(/\//g,' ').match(/[^.!?]+[.!?]*/g).map(sentence=>sentence.trim().split(/(?<=,)|\s+(?=(?:because|although|while|but|and|which|that)\b)/).filter(Boolean).map(c=>'<button class="vchunk say" data-say="'+esc(c)+'">'+esc(c)+'</button>').join('')).join('')+'<p class="muted">'+esc(s[2])+'</p></article>').join('');}
 if(V.mode==='read'){box.innerHTML='<h3>全文を読んで、内容も確認する</h3><p>'+vWords(l)+'語 · 語数 ÷ 実測時間でWPMを計算</p><div class="row"><button class="btn primary" id="vReadStart">計測を始める</button><button class="btn" id="vReadEnd" '+(!V.readAt?'disabled':'')+'>読み終えた</button><span id="vWpm">'+(V.readDone?V.readDone+' WPM':'')+'</span></div><div id="vReadText" '+(!V.readAt&&!V.readDone?'hidden':'')+'>'+l.sl.map(s=>'<p>'+esc(s[1].replace(/\//g,' '))+'</p>').join('')+'</div>';$('#vReadStart').onclick=()=>{V.readAt=Date.now();V.readDone=0;$('#vReadText').hidden=false;$('#vReadEnd').disabled=false;$('#vWpm').textContent='計測中';};$('#vReadEnd').onclick=()=>{if(!V.readAt)return;V.readDone=Math.round(vWords(l)*60000/Math.max(1000,Date.now()-V.readAt));V.readAt=0;$('#vWpm').textContent=V.readDone+' WPM · 設問で理解も確認しましょう';$('#vReadEnd').disabled=true;};}
 if(V.mode==='pron'){const text=l.sl[V.slide][1].replace(/\//g,' '),allText=l.sl.map(x=>x[1].replace(/\//g,' '));box.innerHTML='<h3>この場面で発音チェック</h3><label class="small">文を選ぶ（この教材の'+l.sl.length+'文） <select id="vPronPick" class="vpick">'+l.sl.map((x,i)=>'<option value="'+i+'"'+(i===V.slide?' selected':'')+'>'+(i+1)+'. '+esc(x[1].replace(/\//g,' ').slice(0,70))+'</option>').join('')+'</select></label><p>'+esc(text)+'</p><button class="btn say" data-say="'+esc(text)+'">お手本を聞く</button><p class="muted small">音声入力の文字照合は発音の正確さを保証しません。音素の確認は発音コーチへ。</p><textarea id="vHeard" aria-label="音声入力された英文" placeholder="端末の音声入力で話した結果を入れる"></textarea><div class="row"><button class="btn" id="vCheckPron">文字を照合</button><a class="btn primary" href="'+esc(coachURL(text,allText))+'" target="_blank" rel="noopener">発音コーチで録音</a></div><div id="vPronResult"></div>';$('#vPronPick').onchange=e=>{vStop();V.slide=+e.target.value;vDraw();};$('#vCheckPron').onclick=()=>{if(!$('#vHeard').value.trim())return;const r=judgeInto($('#vPronResult'),text,$('#vHeard').value,true);if(r){bump({pron:1});videoMistake(l.id+'-pron-'+V.slide,text,'手本: '+text,l.id,'発音の文字照合・要確認',r.missed.length===0);}};}
 if(['cloze','build'].includes(V.mode))vCloze();if(V.mode==='speed')vSpeed();if(V.mode==='phrases')vPhrase();if(V.mode==='hvpt')vHVPT();if(V.mode==='fluency')vFluency();vCaptionUpdate();
}
function vPhrase(){const l=V.lesson,box=$('#vActivity'),cards=l.cards;if(V.phrase>=cards.length){box.innerHTML='<h3>このセットは完了です</h3><p>'+cards.length+'フレーズを1回ずつ練習しました。苦手な表現はマイページに保存しました。次の復習時刻は間隔反復で管理されます。</p><button class="btn" data-go="you">マイページへ</button>';return;}const c=cards[V.phrase];V.slide=V.phrase;vDraw();box.innerHTML='<p>フレーズ '+(V.phrase+1)+' / '+cards.length+'</p><h3>'+esc(c[2])+'</h3><p>'+esc(c[4])+'</p>'+(V.revealed?'<h3>'+esc(c[1])+'</h3><p>'+esc(c[3])+'</p><button class="btn say" data-say="'+esc(c[3])+'">例文を聞く</button><div class="row">'+['もう一度','難しい','覚えた','簡単'].map((t,i)=>'<button class="btn" data-vgrade="'+(i+1)+'">'+t+'</button>').join('')+'</div>':'<button class="btn primary" id="vReveal">答えを見る</button>');if($('#vReveal'))$('#vReveal').onclick=()=>{V.revealed=true;vPhrase();};$$('[data-vgrade]',box).forEach(b=>b.onclick=()=>{if(!V.revealed)return;V.revealed=false;const g=+b.dataset.vgrade;reviewCard({id:c[0],en:c[1],ja:c[2],ex:c[3],exJa:c[4]},g);videoMistake(c[0],c[2],c[1]+' — '+c[3],l.id,'フレーズ',g>=3);V.phrase++;vPhrase();});}
function vHVPT(){const l=V.lesson,box=$('#vActivity');if(V.hp>=l.pairs.length){box.innerHTML='<h3>聞き分けセット完了</h3><p>'+l.pairs.length+'問を終了しました。間違えた音はマイページで確認できます。</p><button class="btn" data-go="you">マイページへ</button>';return;}const p=l.pairs[V.hp],correct=V.hpOrder[V.hp];box.innerHTML='<h3>'+l.t+' · '+(V.hp+1)+' / '+l.pairs.length+'</h3><p class="muted small">端末の合成音声による練習です。自然音声を使うセットはマイページの聞き分けから。</p><button class="btn primary" id="vHPPlay">▶ 音を聞く</button><div class="row">'+p.map((w,i)=>'<button class="btn" data-vhp="'+i+'" '+(!V.hpHeard||V.hpDone?'disabled':'')+'>'+esc(w)+'</button>').join('')+'</div><p role="status" id="vHPFeedback"></p><button id="vHPNext" class="btn" '+(!V.hpDone?'hidden':'')+'>次へ</button>';$('#vHPPlay').onclick=async()=>{const token=++V.hpToken;V.hpHeard=false;$('#vHPPlay').disabled=true;await speak(p[correct],1,randVoice());if(token!==V.hpToken||curTab!=='watch'||V.mode!=='hvpt')return;$('#vHPPlay').disabled=false;if(SPEAKERR){$('#vHPFeedback').textContent='再生できませんでした。もう一度再生してください。';return;}V.hpHeard=true;$$('[data-vhp]',box).forEach(b=>b.disabled=V.hpDone);};$$('[data-vhp]',box).forEach(b=>b.onclick=()=>{if(!V.hpHeard||V.hpDone)return;V.hpDone=true;const ok=+b.dataset.vhp===correct;videoMistake(l.id+'-'+V.hp,p.join(' / '),p[correct],l.id,'聞き分け',ok);bump({perc:1,percOk:ok?1:0});$$('[data-vhp]',box).forEach(x=>x.disabled=true);$('#vHPFeedback').textContent=(ok?'正解':'正解は '+p[correct])+' · '+p.join(' / ');$('#vHPNext').hidden=false;});$('#vHPNext').onclick=()=>{V.hpToken++;V.hp++;V.hpHeard=false;V.hpDone=false;vHVPT();};}
function vFluency(){const l=V.lesson;$('#vActivity').innerHTML='<div class="vspeechPlan"><h3>4分で話すための6つの手がかり</h3><p>短い原文を読み上げる課題ではありません。この話を基に、自分の判断と具体例を加えて話します。各項目を約40秒で説明し、次は同じ内容を3分、2分にまとめます。</p><ol><li>登場人物・場所・目的を説明する。</li><li>起きた問題と、その影響を具体的に説明する。</li><li>二つの対応案を比べ、長所と短所を挙げる。</li><li>自分なら何を選ぶか、理由を二つ挙げる。</li><li>似た経験を話す。なければ仮想の例として説明する。</li><li>結果を確認する方法と、相手への質問を述べる。</li></ol><p>話し始めの例：The main issue was… / One option would be… / I would choose… because… / To check the result, I would…</p></div><div id="vFluencyBody"></div>';if(LF.topic!==l.t){LF.round=0;LF.results=[];LF.draft=' ';LF.topic=l.t;}labFluency();$('#vFluencyBody').append(...$('#labBody').childNodes);$('#labFTopic').disabled=true;}
const oldLabFluencyV=labFluency;labFluency=function(){if(curTab==='watch'&&V.mode==='fluency'&&$('#vFluencyBody'))$('#vFluencyBody').replaceChildren();oldLabFluencyV();if(curTab==='watch'&&V.mode==='fluency'&&$('#vFluencyBody')){$('#vFluencyBody').replaceChildren(...$('#labBody').childNodes);$('#labFTopic').disabled=true;}};
// No learning card is put back into the same session: its due date applies later.
const oldBuildQueueV=buildQueue;buildQueue=function(){oldBuildQueueV();W.queue=Array.from(new Map(W.queue.map(c=>[c.id,c])).values()).slice(0,20);W.sessionTotal=W.queue.length;W.sessionDone=0;};
grade=function(g){const c=W.cur;if(!c||!W.revealed)return;W.revealed=false;reviewCard(c,g);videoMistake(c.id,c.ja,c.en,c.id,'フレーズ',g>=3);W.sessionDone=(W.sessionDone||0)+1;nextCard();if(!W.cur){$('#wStage').innerHTML='<h2>今回の練習は完了です</h2><p>'+W.sessionDone+'枚を練習しました。次の復習時刻まで同じカードを繰り返しません。</p><button class="btn" data-go="you">苦手な項目を確認</button>';}};
// マイページ: videos stay as video cards; tools and settings are a plain menu list (not video look-alikes).
const VCHEV='<svg class="vmchev" viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M9 5l7 7-7 7"/></svg>';
const VGEAR='<svg viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="3.2"/><path d="M19.4 15a1.7 1.7 0 0 0 .3 1.8l.1.1a2 2 0 1 1-2.8 2.8l-.1-.1a1.7 1.7 0 0 0-1.8-.3 1.7 1.7 0 0 0-1 1.5V21a2 2 0 1 1-4 0v-.1a1.7 1.7 0 0 0-1.1-1.5 1.7 1.7 0 0 0-1.8.3l-.1.1a2 2 0 1 1-2.8-2.8l.1-.1a1.7 1.7 0 0 0 .3-1.8 1.7 1.7 0 0 0-1.5-1H3a2 2 0 1 1 0-4h.1a1.7 1.7 0 0 0 1.5-1.1 1.7 1.7 0 0 0-.3-1.8l-.1-.1a2 2 0 1 1 2.8-2.8l.1.1a1.7 1.7 0 0 0 1.8.3H9a1.7 1.7 0 0 0 1-1.5V3a2 2 0 1 1 4 0v.1a1.7 1.7 0 0 0 1 1.5 1.7 1.7 0 0 0 1.8-.3l.1-.1a2 2 0 1 1 2.8 2.8l-.1.1a1.7 1.7 0 0 0-.3 1.8V9a1.7 1.7 0 0 0 1.5 1H21a2 2 0 1 1 0 4h-.1a1.7 1.7 0 0 0-1.5 1z"/></svg>';
function vMenuRow({t,m,go,href,icon}){const inner='<span class="vmic">'+icon+'</span><span class="vmtx"><b>'+esc(t)+'</b>'+(m?'<small>'+esc(m)+'</small>':'')+'</span>'+VCHEV;return href?'<a class="vmrow" href="'+esc(href)+'" target="_blank" rel="noopener">'+inner+'</a>':'<button class="vmrow" data-go="'+esc(go)+'">'+inner+'</button>';}
function vFeatureRow(f){return vMenuRow({t:f.t,m:f.m(),go:f.go,href:f.href?f.href():null,icon:vAvatarIcon(vSceneItem(f.sc),f.av[1])});}
function vLineIcon(svg,color){return '<span class="av vav vline" style="--c:'+color+'" aria-hidden="true">'+svg+'</span>';}
const oldYouV=renderYou;renderYou=function(){oldYouV();const body=$('#youBody');body.querySelectorAll(':scope > .vgrid').forEach(g=>g.remove());
 const rows=Object.entries(S.meta.videoMistakes?.rows||{}).filter(([,m])=>!m.resolved).sort((a,b)=>b[1].at-a[1].at);
 const today=FEATURES.find(f=>f.go==='today'),stats=FEATURES.find(f=>f.go==='stats');
 let h='<div class="vmenu">'+(today?vFeatureRow(today):'')+vMenuRow({t:'学習記録とスコア',m:'学習時間・スコアの記録',go:'stats',icon:vLineIcon('<svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/></svg>','#606060')})+vMenuRow({t:'設定',m:'目標・読み上げの声と速度・発音コーチの URL',go:'stats:settings',icon:vLineIcon(VGEAR,'#606060')})+'</div>';
 h+='<h2>間違えた・思い出せなかった項目</h2><div class="stack">'+(rows.length?rows.map(([id,m])=>'<article class="vtranscript"><span class="muted small">'+esc(m.kind)+'</span><h3>'+esc(m.prompt)+'</h3><details><summary>答えを確認</summary><p>'+esc(m.answer)+'</p></details><div class="row">'+(VC.some(x=>x.id===m.lessonId)?'<button class="btn sm" data-video="'+esc(m.lessonId)+'">この教材を復習</button>':'<button class="btn sm" data-go="words">フレーズ復習へ</button>')+'<button class="btn sm" data-vresolve="'+esc(id)+'">復習できた</button></div></article>').join(''):'<p class="muted">まだ記録はありません。設問・想起・フレーズ・聞き分けの結果がここにまとまります。</p>')+'</div>';
 h+='<h2>自分で選んで練習</h2><div class="vmenu">'+LAB_MODES.map(m=>vMenuRow({t:m[1],m:m[3],go:'lab:'+m[0],icon:vLineIcon(ICON[m[2]]||'','#065FD4')})).join('')+FEATURES.filter(f=>f.cat!=='you'&&f.go!=='today').map(vFeatureRow).join('')+'</div>';
 h+='<h2>教材を自分で選ぶ</h2>'+[['長文リーディング・リスニング',l=>l.id.startsWith('long-')],['追加フレーズ（TOEICなど）',l=>!!l.cards&&!l.id.startsWith('deck-')],['生活・会話フレーズ',l=>l.id.startsWith('deck-')],['聞き分け（HVPT）セット',l=>l.id.startsWith('contrast-')],['4 / 3 / 2 スピーキング',l=>l.id.startsWith('talk-')],['NYなどの聞く教材',l=>l.id.startsWith('passage-')]].map(([name,f])=>{const list=VC.filter(f);return list.length?'<details class="vpick"><summary>'+esc(name)+' <span class="muted small">'+list.length+'本</span></summary><div class="vgrid vcompact">'+list.map(vCard).join('')+'</div></details>':'';}).join('');
 body.insertAdjacentHTML('beforeend',h);};
// Settings: gear in the top bar, like YouTube.
$('#sync').insertAdjacentHTML('afterend','<button class="gearbtn" id="vGear" data-go="stats:settings" aria-label="設定" title="設定">'+VGEAR+'</button>');
function vShowSettings(){requestAnimationFrame(()=>{const card=$('#stCoach')?.closest('.card');if(!card)return;card.id='settingsCard';card.scrollIntoView({block:'start',behavior:'smooth'});card.classList.remove('vflash');void card.offsetWidth;card.classList.add('vflash');});}
const VPRACTICE_ICON={'p:recall':'book','p:perc':'wave','p:cloze':'magnifier','p:question':'chat','p:speed':'clock','p:say':'note','p:lesson':'bulb'};
function vDecorateAv(av,key){if(!av||!key)return;const item=VAVI[key]||VPRACTICE_ICON[key]||'book',color=(typeof GCOL!=='undefined'&&GCOL[key])||(typeof PCOL!=='undefined'&&PCOL[key.slice(2)])||'#4a5568';av.className='av vav';av.style.setProperty('--c',color);av.style.background='';av.innerHTML=vIcon(item);}
const oldFeedCardV=renderFeedCard;renderFeedCard=function(c){const el=oldFeedCardV(c);try{const av=el&&el.querySelector&&el.querySelector('.av');if(av&&PCOL[c.type])vDecorateAv(av,'p:'+c.type);}catch(e){}return el;};
const oldSubsV=renderSubs;renderSubs=function(){oldSubsV();$$('[data-subsel]').forEach(b=>vDecorateAv(b.querySelector('.av'),b.dataset.subsel));$$('.subrow').forEach(row=>vDecorateAv(row.querySelector('.av'),row.querySelector('[data-sub]')?.dataset.sub));};
const oldShelfV=shelfHTML;shelfHTML=function(title,list){return list.length?oldShelfV(title,list):'';};
let vPracticeIndex=0,vShortIndex=0,vShortBag=[];
nextItem=function(){SH.since++;if(SH.since%7===0&&typeof makeWQ==='function'){const q=makeWQ();if(q)return q;}if(SH.since%3===0&&typeof genPractice==='function'){const c=genPractice();if(c)return {type:'practice',c};}if(SH.since%5===0){const modes=['phrases','recall','hvpt','cloze','build','questions','speed','read','chunks','pron'],mode=modes[vPracticeIndex%modes.length],sets=VC.filter(l=>l.defaultMode===mode),l=sets[Math.floor(vPracticeIndex++/modes.length)%sets.length];const s=l.sl[0];return {type:'short',s:{id:'practice-video-'+l.id,g:l.g,t:l.t,videoId:l.id,sl:[[s[0],'Listen, then try to recall the meaning.','聞いてから意味を思い出しましょう。'],s,[s[0],'Now say it in your own words. Open the lesson to check your answer.','自分の言葉で説明。右の「詳しく学ぶ」で答え合わせへ。']],w:[],q:null}};}if(!vShortBag.length){vShortBag=shuffle(shortsAll());const i=vShortBag.findIndex(s=>s.g!=='dino');if(i>0)[vShortBag[0],vShortBag[i]]=[vShortBag[i],vShortBag[0]];}const s=vShortBag.shift();SH.lastG=s.g;return {type:'short',s};};
const oldRailV=railHTML;railHTML=function(it){return oldRailV(it).replace('<div class="rail">','<div class="rail"><button data-r="detail"><span class="ic">'+ICON.book+'</span>詳しく学ぶ</button>');};
function vShortDetail(it){spStop();const s=it.s;if(!VC.some(x=>x.id===s.id)&&!s.videoId)VC.push({...s,kind:'listen',level:'A2–B2',defaultMode:'recall',qs:vShortQs(s)});openVideo(s.videoId||s.id);}
const oldWireV=wireRail;wireRail=function(it,el){oldWireV(it,el);const b=el.querySelector('[data-r="detail"]');if(b)b.onclick=e=>{e.stopPropagation();vShortDetail(it);};};
const oldRenderShortV=renderShort;renderShort=function(it){const el=oldRenderShortV(it);if(it.type==='short'){let start=null,suppress=false;el.addEventListener('pointerdown',e=>{if(!e.target.closest('button:not(.tapz),input,a,.sheet'))start={x:e.clientX,y:e.clientY};});el.addEventListener('pointercancel',()=>start=null);el.addEventListener('pointerup',e=>{if(!start)return;const dx=e.clientX-start.x,dy=e.clientY-start.y;start=null;if(dx< -65&&Math.abs(dx)>Math.abs(dy)*1.3){suppress=true;vShortDetail(it);}});el.addEventListener('click',e=>{if(suppress){suppress=false;e.stopImmediatePropagation();e.preventDefault();}},true);}return el;};
let vAutoNext=null;
const oldSpStopV=spStop;spStop=function(){clearTimeout(vAutoNext);oldSpStopV();};
const oldShortEndV=shortEnd;shortEnd=function(it){oldShortEndV(it);it.quizOpen=false;const ov=it.el.querySelector('.endov');const n=vShortQs(it.s).length;
 ov.innerHTML='<div style="font-size:17px;font-weight:700">'+esc(it.s.t)+'</div><p data-vloop>何もしなければ、もう一度再生します</p><div class="row">'+(n?'<button class="btn primary" data-vquiz>設問に答える（'+n+'問）</button>':'')+'<button class="btn" data-vagain>もう一度見る</button><button class="btn" data-vstay>ここで止める</button></div><div class="row"><button class="btn" data-vdetail>詳しく学ぶ →</button><button class="btn" data-vnext>次の動画へ ↓</button></div><p class="small" style="opacity:.7">次の動画へは上にスワイプ（PC はホイール）でも進めます。</p>';
 const q=ov.querySelector('[data-vquiz]');if(q)q.onclick=()=>vShortQuiz(it);
 ov.querySelector('[data-vagain]').onclick=()=>spPlay(it,0);
 ov.querySelector('[data-vstay]').onclick=()=>{clearTimeout(vAutoNext);ov.querySelector('[data-vloop]').textContent='停止中';};
 ov.querySelector('[data-vdetail]').onclick=()=>vShortDetail(it);
 ov.querySelector('[data-vnext]').onclick=()=>vShortNext(it);
 const token=SP.tok;vAutoNext=setTimeout(()=>{if(curTab!=='shorts'||SH.active!==it.i||SP.tok!==token)return;spPlay(it,0);},VLOOP_MS);};
const VLOOP_MS=2500;
function vShortNext(it){clearTimeout(vAutoNext);if(it.i+1>=SH.items.length)shAppend(3);shGo(it.i+1);}
const oldSizeShortsV=sizeShorts;sizeShorts=function(){const w=$('#shWrap');const mobile=matchMedia('(max-width:719px)').matches;document.body.classList.toggle('ee-shorts-full',mobile&&curTab==='shorts');if(mobile){if($('#p-shorts').hidden)return;const navH=$('#nav').offsetHeight;const vh=(window.visualViewport?visualViewport.height:innerHeight);Object.assign(w.style,{position:'fixed',top:'0',left:'0',right:'0',width:'100%',maxWidth:'none',marginInline:'0',height:Math.max(360,vh-navH)+'px'});return;}Object.assign(w.style,{position:'',top:'',left:'',right:'',width:''});oldSizeShortsV();if(innerWidth>=720){w.style.maxWidth=Math.min(640,innerWidth-190)+'px';w.style.width='100%';}};
window.visualViewport?.addEventListener('resize',()=>sizeShorts());
document.addEventListener('click',e=>{const v=e.target.closest('[data-video]');if(v){openVideo(v.dataset.video);return;}const r=e.target.closest('[data-vresolve]');if(r){const m=S.meta.videoMistakes.rows[r.dataset.vresolve];videoMistake(r.dataset.vresolve,m.prompt,m.answer,m.lessonId,m.kind,true);renderYou();}const b=e.target.closest('[data-vscroll]');if(b){const row=b.closest('.vrow').querySelector('.shelf,.chrow');row.scrollBy({left:Number(b.dataset.vscroll)*row.clientWidth*.85,behavior:'smooth'});}});

// PC: YouTube-style arrow buttons on every horizontal row (shorts shelves, channel list). Phones just swipe.
const VARROW='<svg viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><path d="M9 5l7 7-7 7"/></svg>';
function vArrowState(row){const wrap=row.parentElement;if(!wrap?.classList.contains('vrow'))return;const max=row.scrollWidth-row.clientWidth;const set=(el,v)=>{if(el.hidden!==v)el.hidden=v;};set(wrap.querySelector('.vsarrow.l'),row.scrollLeft<=4);set(wrap.querySelector('.vsarrow.r'),row.scrollLeft>=max-4);}
function vArrowize(){$$('.shelf:not([data-varrow]),.chrow:not([data-varrow])').forEach(row=>{row.dataset.varrow='1';const wrap=document.createElement('div');wrap.className='vrow'+(row.classList.contains('chrow')?' vrow-ch':'');row.parentNode.insertBefore(wrap,row);wrap.append(row);wrap.insertAdjacentHTML('beforeend','<button class="vsarrow l" data-vscroll="-1" aria-label="左へ送る">'+VARROW+'</button><button class="vsarrow r" data-vscroll="1" aria-label="右へ送る">'+VARROW+'</button>');row.addEventListener('scroll',()=>vArrowState(row),{passive:true});requestAnimationFrame(()=>vArrowState(row));});}
if(typeof MutationObserver!=='undefined'&&document.body){let vArrowRaf=0;const vArrowAll=()=>{cancelAnimationFrame(vArrowRaf);vArrowRaf=requestAnimationFrame(()=>{vArrowize();$$('.vrow>.shelf,.vrow>.chrow').forEach(vArrowState);});};new MutationObserver(vArrowAll).observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:['hidden']});window.addEventListener('resize',vArrowAll);vArrowAll();}
window.addEventListener('pagehide',()=>{vStop();clearTimeout(vAutoNext);});
// Fixed feed-style episodes: the clicked card determines the task and sentence.
VWORDS.forEach((c,i)=>{if(i%4!==0)return;const mode=i%8===0?'cloze':'build';VC.push({id:'guided-'+mode+'-'+c[0],g:'words',t:c[2]+' · '+VMODES[mode],kind:'practice',level:i<48?'A2–B1':'B1–B2',defaultMode:mode,practiceCard:c,sl:[['paper|book|bulb',c[3],c[4]]],qs:[]});});
EE_LONG.forEach(l=>['questions','chunks','read','speed','pron'].forEach(mode=>VC.push({...l,id:'guided-'+mode+'-'+l.id,t:l.t+' · '+VMODES[mode],defaultMode:mode})));
function vCloze(){const l=V.lesson,c=l.practiceCard,box=$('#vActivity'),prompt=V.mode==='build'?shuffle(c[3].replace(/[.!?]/g,'').split(/\s+/)).join(' / '):c[3].toLowerCase().includes(c[1].toLowerCase())?c[3].replace(new RegExp(c[1].replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i'),'________'):c[4];box.innerHTML='<h3>'+VMODES[V.mode]+' · この1文を完成させる</h3><p>'+esc(prompt)+'</p><p class="muted">'+esc(c[4])+'</p><textarea id="vTyped" aria-label="英文の答え" placeholder="英語で答えを入力"></textarea><button id="vTypedCheck" class="btn primary">答え合わせ</button><p id="vTypedResult" role="status"></p>';$('#vTypedCheck').onclick=()=>{const answer=$('#vTyped').value.trim();if(!answer)return;const normalize=x=>x.toLowerCase().replace(/[^a-z0-9 ]/g,'').replace(/\s+/g,' ').trim();const expected=V.mode==='build'?c[3]:c[1];const ok=normalize(answer)===normalize(expected)||normalize(answer)===normalize(c[3]);videoMistake(l.id,prompt,c[3],l.id,VMODES[V.mode],ok);$('#vTypedResult').textContent=(ok?'一致しました':'手本と比べてみましょう')+' · '+c[3];$('#vTypedCheck').disabled=true;vCaptionUpdate();};}
function vSpeed(){const box=$('#vActivity');box.innerHTML='<h3>同じ内容を速度を変えて聞く</h3><p>この動画の全文を、等速 → 1.2倍 → 等速で聞きます。意味が追えなくなったら等速に戻してください。</p><div class="row">'+[1,1.2,1].map((r,i)=>'<button class="btn" data-vspeed="'+r+'">'+(i+1)+'回目 · '+r+'倍</button>').join('')+'</div><p class="muted">全文は「スクリプト」、理解の確認は「設問」から。</p>';$$('[data-vspeed]',box).forEach(b=>b.onclick=()=>{vStop();V.slide=0;V.rate=+b.dataset.vspeed;$('#vRate').value=V.rate;vPlay();});}
// Mirror recall grades into the existing spaced-review scheduler.
videoSection.addEventListener('click',e=>{const b=e.target.closest('[data-vremember]');if(!b||!V.lesson?.microId)return;const id=V.lesson.microId;put('progress',id,{...schedule(S.progress[id],b.dataset.vremember==='1'?3:1),id});});
const oldGradeQsV=gradeQs;gradeQs=function(qs,prefix,p,out){const result=oldGradeQsV(qs,prefix,p,out);qs.forEach((q,i)=>{const sel=document.querySelector('input[name="'+prefix+i+'"]:checked');videoMistake('legacy-'+p.id+'-'+i,q.q,q.c[q.a],p.id,'設問',!!sel&&+sel.value===q.a);});return result;};
const oldFeedAnswerV=feedAnswer;feedAnswer=function(c,el,ok,msg,fbEl){if(!c.done&&!['lesson','learn','box','story'].includes(c.type)){const prompt=c.card?.ja||c.q?.q||c.ja||c.pair?.join(' / ')||c.text||(c.s?sentText(c.s):'フィードの練習');const answer=c.card?.en||c.q?.c[c.q.a]||c.words?.join(' ')||(c.pair?c.pair[c.k]:null)||c.text||(c.s?sentText(c.s):'');if(answer)videoMistake('feed-'+vHash(c.type+prompt),prompt,answer,c.card?.id||'',PCH[c.type]||'フィード',ok);}return oldFeedAnswerV(c,el,ok,msg,fbEl);};
const oldLabRecallV=labRecall;labRecall=function(){oldLabRecallV();const item=EE_MICRO.find(x=>x.id===LAB.id);$$('[data-labrate]').forEach(b=>{const handler=b.onclick;b.onclick=e=>{const rated=LAB.rated;handler(e);if(!rated&&LAB.rated)videoMistake(item.id,item.japanese,item.english,'recall-'+item.id,'想起',+b.dataset.labrate>=3);};});};
const oldLabHPNextV=labHPNext;labHPNext=function(){oldLabHPNextV();$$('[data-hpanswer]').forEach(b=>{const handler=b.onclick;b.onclick=e=>{const done=LP.answered;handler(e);if(!done&&LP.answered)videoMistake('pair-'+LP.cur.pair.join('-'),LP.cur.pair.join(' / '),LP.cur.pair[LP.cur.answer],'','聞き分け',+b.dataset.hpanswer===LP.cur.answer);};});};
function vCaptionUpdate(){if(!V.lesson||!$('#vCaption'))return;const s=V.lesson.sl[V.slide];const hidden=(V.mode==='phrases'&&!V.revealed&&V.phrase<V.lesson.cards.length)||(V.mode==='recall'&&!$('#vActivity details')?.open)||(['cloze','build'].includes(V.mode)&&!$('#vTypedCheck')?.disabled);$('#vCaption').innerHTML=hidden?'<div>思い出してから、<br>答えを確認しよう。</div><small>'+esc(s[2]||'')+'</small>':'<div>'+esc(s[1].replace(/\//g,' '))+'</div><small>'+esc(s[2]||'')+'</small>';}
videoSection.addEventListener('toggle',e=>{if(e.target.matches('details'))vCaptionUpdate();},true);


// Coach links point at the local pronunciation coach; remind how to start it when it is on this PC.
document.addEventListener('click',e=>{const a=e.target.closest('a[href]');if(!a)return;const base=String(settings().coach||'http://127.0.0.1:7860');if(!a.href.startsWith(base.replace(/\/+$/,'')))return;if(/127\.0\.0\.1|localhost/.test(base)){const phone=/Android|iPhone|iPad/i.test(navigator.userAgent);const msg=phone?'スマホでは、マイページの設定「発音コーチのURL」に共有URLかSpacesのURLを入れてください':'開けないときは、pron-coach フォルダーの start_coach.bat を起動してから押し直してください';toast(msg);vCoachHint={msg,at:Date.now()};}},true);
let vCoachHint=null;document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&vCoachHint&&Date.now()-vCoachHint.at<120000){toast(vCoachHint.msg);vCoachHint=null;}});
// ---- Mobile-safe speech (iOS Safari / Android Chrome) ----
// 1) iOS only allows speech that starts inside a tap: speak a silent utterance on the first touch to unlock it.
// 2) cancel() immediately followed by speak() drops the new utterance on many phones: cancel only when busy, then wait a moment.
// 3) "interrupted"/"canceled" errors come from our own cancel() and are not failures.
let vSpeechPrimed=false;
let vLastCancel=0;
stopSpeech=function(){playTok++;try{const ss=speechSynthesis;if(ss.speaking||ss.pending){ss.cancel();vLastCancel=Date.now();}}catch(e){}};
function vPrimeSpeech(){if(vSpeechPrimed||!('speechSynthesis' in window))return;vSpeechPrimed=true;try{const u=new SpeechSynthesisUtterance(' ');u.volume=0;u.lang='en-US';speechSynthesis.speak(u);}catch(e){}if(!voices.length)try{loadVoices();}catch(e){}}
['touchend','pointerup','click','keydown'].forEach(ev=>document.addEventListener(ev,vPrimeSpeech,{capture:true,passive:true}));
const vNav=typeof navigator!=='undefined'?navigator:{userAgent:'',platform:'',maxTouchPoints:0};const vMobileSpeech=/Android|iPhone|iPad|iPod/i.test(vNav.userAgent)||(vNav.platform==='MacIntel'&&vNav.maxTouchPoints>1);
speak=function(text,mul,voice,keep,onb){
 if(!('speechSynthesis' in window)){toast('この端末では英語の読み上げが使えません');return Promise.resolve();}
 if(!keep)playTok++;
 const ss=speechSynthesis;SPEAKERR=null;
 if(!voices.length)try{loadVoices();}catch(e){}
 let busy=ss.speaking||ss.pending;if(busy){try{ss.cancel();}catch(e){}vLastCancel=Date.now();}busy=busy||Date.now()-vLastCancel<150;
 try{if(ss.paused)ss.resume();}catch(e){}
 const u=new SpeechSynthesisUtterance(String(text));let v=voice||pickVoice();
 if(v&&!ss.getVoices().some(x=>x.voiceURI===v.voiceURI))v=null; // stale voice objects are ignored silently on some phones
 if(v){u.voice=v;u.lang=v.lang;}else u.lang='en-US';
 const rate=Math.max(0.4,Math.min(1.8,(settings().rate||1)*(mul||1)));u.rate=rate;
 if(onb)u.onboundary=e=>{if(typeof e.charIndex==='number')onb(e.charIndex);};
 return new Promise(res=>{let done=false,started=false;const fin=()=>{if(!done){done=true;res();}};
  u.onstart=()=>{started=true;};u.onend=fin;
  u.onerror=e=>{const er=e&&e.error;if(er&&er!=='interrupted'&&er!=='canceled')SPEAKERR=er;fin();};
  setTimeout(()=>{if(!started&&!done&&vMobileSpeech&&!ss.speaking)SPEAKERR=SPEAKERR||'no-start';fin();},Math.max(3000,String(text).length*120/rate));
  const go=()=>{try{ss.speak(u);}catch(e){SPEAKERR='error';fin();}};
  if(busy&&vMobileSpeech)setTimeout(go,120);else go();});
};
// Settings: show what the device offers, so a silent phone can be diagnosed.
function vSpeechDiag(){const el=$('#vSpeechDiag');if(!el)return;if(!('speechSynthesis' in window)){el.textContent='この端末・ブラウザーは読み上げに対応していません。';return;}const en=speechSynthesis.getVoices().filter(v=>/^en/i.test(v.lang));el.textContent='英語の声：'+en.length+'個'+(en.length?'（'+en.slice(0,3).map(v=>v.name).join('、')+(en.length>3?' ほか':'')+'）':'。端末の設定で英語の音声データを入れると使えます。')+(SPEAKERR?' ／ 直前のエラー：'+SPEAKERR:'');}
{const t=$('#stTest');if(t&&t.insertAdjacentHTML){t.insertAdjacentHTML('afterend','<p class="small muted" id="vSpeechDiag"></p><p class="small muted">音が出ないとき：音量・マナーモード（iPhone は横のスイッチ）を確認し、一度画面をタップしてから再生してください。Android は「設定 → システム → 言語 → 音声出力（テキスト読み上げ）」で英語の音声データを入れてください。</p>');t.addEventListener('click',()=>setTimeout(vSpeechDiag,1500));if('speechSynthesis' in window)speechSynthesis.addEventListener?.('voiceschanged',vSpeechDiag);setTimeout(vSpeechDiag,800);}}
// Opening English Express with ?coach=<url> (the QR code printed by start_coach_phone.bat) saves the coach URL once.
(function(){try{if(typeof location==='undefined'||!location.search)return;const q=new URLSearchParams(location.search);const c=q.get('coach');if(!c)return;const u=new URL(c);const ok=(u.protocol==='https:'&&/(^|\.)(gradio\.live|hf\.space)$/i.test(u.hostname))||/^(127\.0\.0\.1|localhost)$/i.test(u.hostname);if(ok){const v=(u.origin+u.pathname).replace(/\/+$/,'');saveSettings({coach:v});if($('#stCoach'))$('#stCoach').value=v;setTimeout(()=>toast('発音コーチのURLを保存しました（'+u.hostname+'）'),600);}q.delete('coach');history.replaceState(null,'',location.pathname+(q.toString()?'?'+q.toString():'')+location.hash);}catch(e){}})();

// ---- Pronunciation coach: pass the whole lesson so the coach can list it sentence by sentence.
coachURL=function(text,passage){const base=String(settings().coach||'http://127.0.0.1:7860').trim().replace(/\/+$/,'');const t=String(text||'').replace(/\s+/g,' ').trim();const all=(Array.isArray(passage)?passage:[passage]).map(x=>String(x||'').replace(/\//g,' ').replace(/\s+/g,' ').trim()).filter(Boolean).join('\n');const q=[];if(t)q.push('text='+encodeURIComponent(t));if(all&&all!==t)q.push('passage='+encodeURIComponent(all.slice(0,6000)));return base+'/'+(q.length?'?'+q.join('&'):'');};
// Shorts: the speak sheet lets you pick any sentence of the short, not only the one on screen.
const VPROMPT=/^(How would you say this|Listen, then try|Now say it in your own words)/i;
function vShortLines(s){return (s.sl||[]).map((sl,i)=>({i,en:slideText(sl),ja:sl[2]||''})).filter(x=>x.en&&!VPROMPT.test(x.en));}
openSpeakSheet=function(it,pick){
 spStop();const lines=vShortLines(it.s);if(!lines.length)return;const cur=pick!==undefined?pick:(SP.it===it?SP.slide:0);
 const k=Math.max(0,lines.findIndex(x=>x.i===cur));const sent=lines[k].en;const sh=it.el.querySelector('.sheet');
 if(SP.it===it||pick!==undefined){SP.it=it;SP.slide=lines[k].i;showSlide(it,lines[k].i);}
 sh.innerHTML='<div class="row"><b class="jp">発音チェック</b><span class="spacer"></span><button class="btn sm" data-close>閉じる</button></div>'
  +(lines.length>1?'<label class="small jp">文を選ぶ（この動画の'+lines.length+'文）<select class="vpick" data-vpick>'+lines.map((x,j)=>'<option value="'+x.i+'"'+(j===k?' selected':'')+'>'+(j+1)+'. '+esc(x.en.slice(0,70))+'</option>').join('')+'</select></label>':'')
  +'<div class="target">'+esc(sent)+'</div><div class="row"><button class="btn say sm" data-say="'+esc(sent)+'">手本</button><button class="btn say sm" data-say="'+esc(sent)+'" data-rate="0.7">ゆっくり</button></div><div class="row"><a class="btn primary sm" target="_blank" rel="noopener" href="'+esc(coachURL(sent,lines.map(x=>x.en)))+'">音素分析（発音コーチ）</a><span class="tiny muted jp">録音して音素ごとに採点。コーチでもこの動画の文を1文ずつ選べます</span></div><div class="hintbox">簡易チェック：入力欄をタップしてキーボードのマイク（PC は Win + H）で読む。</div><textarea data-sin placeholder="ここに音声入力"></textarea><button class="btn primary" data-sj>判定する</button><div data-sout class="stack"></div>';
 sh.hidden=false;sh.querySelector('[data-close]').onclick=()=>closeSheet(it);
 const sel=sh.querySelector('[data-vpick]');if(sel)sel.onchange=e=>openSpeakSheet(it,+e.target.value);
 sh.querySelector('[data-sj]').onclick=()=>{const r=judgeInto(sh.querySelector('[data-sout]'),sent,sh.querySelector('[data-sin]').value,true);if(r)bump({pron:1});};
};
// Shorts: questions for every short (its own question if any, plus meaning and listening-cloze questions made from its sentences).
// Blanks and wrong choices use lower-case words only, so names and places are not used.
const VSTOP=new Set('about,after,again,also,been,before,being,because,could,does,each,even,every,from,have,here,into,just,like,made,make,many,more,most,much,only,other,over,said,same,some,such,than,that,their,them,then,there,these,they,this,those,very,were,what,when,where,which,while,will,with,would,your'.split(','));
let VQPOOL=null;const VQCACHE=new Map();
function vQPool(){if(VQPOOL)return VQPOOL;const words=new Set(),ja=new Set();shortsAll().forEach(s=>vShortLines(s).forEach(x=>{if(x.ja)ja.add(x.ja);(x.en.match(/[A-Za-z]+/g)||[]).forEach(w=>{if(w===w.toLowerCase()&&w.length>=4&&!VSTOP.has(w))words.add(w);});}));return VQPOOL={words:[...words].sort(),ja:[...ja].sort()};}
function vPickN(pool,n,seed,avoid){const out=[],seen=new Set(avoid.map(x=>String(x).toLowerCase()));for(let k=0;out.length<n&&k<pool.length*3+30;k++){const c=pool[vHash(seed+':'+k)%pool.length];if(c&&!seen.has(String(c).toLowerCase())){seen.add(String(c).toLowerCase());out.push(c);}}return out;}
function vOrder(choices,seed){const idx=choices.map((_,k)=>k).sort((a,b)=>vHash(seed+'#'+a)-vHash(seed+'#'+b));return [idx.map(k=>choices[k]),idx.indexOf(0)];}
function vShortQs(s){
 const key=(s.id||s.t||'')+'|'+(s.sl||[]).length;if(VQCACHE.has(key))return VQCACHE.get(key).map(q=>[q[0],q[1].slice(),q[2]]);
 const qs=[],seed=s.id||s.t||'short',lines=vShortLines(s),pool=vQPool();
 if(s.q&&Array.isArray(s.q[1])&&s.q[1].length>=2)qs.push([String(s.q[0]),s.q[1].map(String),+s.q[2]||0]);
 const withJa=lines.filter(x=>x.ja);
 if(withJa.length){const m=withJa[vHash(seed+'m')%withJa.length];let wrong=vPickN(withJa.filter(x=>x.ja!==m.ja).map(x=>x.ja),3,seed+'mo',[m.ja]);if(wrong.length<3)wrong=wrong.concat(vPickN(pool.ja,3-wrong.length,seed+'mp',[m.ja,...wrong]));if(wrong.length){const [c,a]=vOrder([m.ja,...wrong],seed+'mq');qs.push(['この文の意味は？「'+m.en+'」',c,a]);}}
 const order=lines.map((x,j)=>j).sort((a,b)=>vHash(seed+'c'+a)-vHash(seed+'c'+b));let cloze=0;
 for(const j of order){if(cloze>=2)break;const en=lines[j].en;const cands=[...new Set((en.match(/[A-Za-z]+/g)||[]).filter(w=>w===w.toLowerCase()&&w.length>=4&&!VSTOP.has(w)))];if(!cands.length)continue;
  const w=cands[vHash(seed+'w'+j)%cands.length],lw=w.toLowerCase();const near=pool.words.filter(x=>Math.abs(x.length-lw.length)<=2&&x!==lw);const wrong=vPickN(near.length>=3?near:pool.words,3,seed+'cw'+j,[lw]);if(wrong.length<1)continue;
  const blanked=en.replace(new RegExp('\\b'+w+'\\b'),'＿＿＿');const [c,a]=vOrder([lw,...wrong],seed+'cq'+j);qs.push(['聞き取り：空所に入る語は？「'+blanked+'」',c,a]);cloze++;}
 VQCACHE.set(key,qs);return qs.map(q=>[q[0],q[1].slice(),q[2]]);
}
function vShortQuiz(it){
 spStop();clearTimeout(vAutoNext);it.quizOpen=true;const ov=it.el.querySelector('.endov');const qs=vShortQs(it.s);let k=0,ok=0,answered=false;
 const tail='<div class="row"><button class="btn sm" data-vq-again>もう一度見る</button><button class="btn sm" data-vq-detail>詳しく学ぶ →</button><button class="btn primary sm" data-vq-next>次の動画へ ↓</button></div>';
 const wire=()=>{ov.querySelector('[data-vq-again]').onclick=()=>{it.quizOpen=false;spPlay(it,0);};ov.querySelector('[data-vq-detail]').onclick=()=>vShortDetail(it);ov.querySelector('[data-vq-next]').onclick=()=>vShortNext(it);};
 const draw=()=>{
  if(!qs.length){ov.innerHTML='<p>この動画からは設問を作れませんでした。</p>'+tail;wire();return;}
  if(k>=qs.length){ov.innerHTML='<div style="font-size:17px;font-weight:700">設問 完了 · '+ok+' / '+qs.length+' 問正解</div><p class="small" style="opacity:.8">間違えた設問はマイページの復習リストに残ります。</p>'+tail;wire();return;}
  const q=qs[k];answered=false;
  ov.innerHTML='<div class="small" style="opacity:.8">設問 '+(k+1)+' / '+qs.length+' · '+esc(it.s.t)+'</div><div style="font-size:17px;font-weight:700">'+esc(q[0])+'</div><div class="choices">'+q[1].map((c,j)=>'<button data-vsq="'+j+'">'+esc(c)+'</button>').join('')+'</div><div data-vsqf></div>'+tail;wire();
  ov.querySelectorAll('[data-vsq]').forEach(b=>b.onclick=()=>{if(answered)return;answered=true;const j=+b.dataset.vsq,right=j===q[2];if(right)ok++;
   ov.querySelectorAll('[data-vsq]').forEach(x=>{if(+x.dataset.vsq===q[2])x.classList.add('right');else if(x===b)x.classList.add('wrong');});
   videoMistake((it.s.id||'short')+'-sq'+k,q[0],q[1][q[2]],it.s.videoId||it.s.id,'ショートの設問',right);bump({compTot:1,compOk:right?1:0});
   const f=ov.querySelector('[data-vsqf]');f.innerHTML='<div class="fb '+(right?'ok':'ng')+'">'+(right?'正解':'正解は「'+esc(q[1][q[2]])+'」')+'</div><button class="btn primary sm" data-vsq-go>'+(k+1<qs.length?'次の設問':'結果を見る')+'</button>';
   f.querySelector('[data-vsq-go]').onclick=()=>{k++;draw();};});
 };
 draw();ov.hidden=false;
}
// While the questions are open, nothing restarts playback behind them (e.g. the first tap that unlocks audio).
const oldSpPlayQ=spPlay;spPlay=function(it,from){if(it&&it.quizOpen&&it.el&&!it.el.querySelector('.endov').hidden)return;if(it)it.quizOpen=false;return oldSpPlayQ(it,from);};
// A "設問" chip on every short: choose it any time to answer questions about this short.
const oldRenderShortQ=renderShort;renderShort=function(it){const el=oldRenderShortQ(it);if(it&&it.type==='short'&&el&&el.querySelector){const h=el.querySelector('.shead'),n=vShortQs(it.s).length;if(h&&n){h.insertAdjacentHTML('beforeend','<button class="vqchip" data-vqchip aria-label="この動画の設問に答える">設問 '+n+'</button>');const b=h.querySelector('[data-vqchip]');if(b)b.onclick=e=>{e.stopPropagation();vShortQuiz(it);};}}return el;};
